### ISSUE TITLE
Incompatible Modules

### ISSUE THREAD

**Issue by Arengorn** [Galadirith/markdown-preview-plus#103]
Using Atom Version 1.0.10
<img width="1326" alt="captura de tela 2015-09-05 as 20 31 51" src="https://cloud.githubusercontent.com/assets/7243783/9701708/311ee712-540d-11e5-9177-e07b225196b4.png">
I'm not sure why I'm getting this, although it renders the package unusable. Could anyone help me out finding why am I getting this incompatibility bug?

**Comment by Galadirith** [comment]
@Arengorn Thanks for posting your issue and really sorry your having a problem. I actually also occasionally get this when I update my (non-development) version of MPP. What usually resolves it is clicking on the **Reload Atom and Recheck Packages** button just above where it lists the incompatible native modules; I am not 100% sure as to why this resolves it but I suspect caching of old files from the previous version.

If that doesn't resolve it it may actually be incompatible modules with Atom. The latest version released a few days ago is `1.0.11`. If you are able to I would suggest trying to update to the newest version of Atom.

I hope one of these candidate solutions resolves your issue. Please let us know how it goes and we'll take it from there. Thanks @Arengorn :D

**Comment by Arengorn** [comment]
Hey @Galadirith thanks a lot for the quick reply! I tried reloading Atom and rechecking packages but nothing quite changed, I still have the bug. Since I was running it on a Ubuntu VM I decided to attempt installing it over at my main OS X machine but with no success. I get the following bug whenever I attempt installing:
>> pathwatcher-without-runas@4.5.0 install >/private/var/folders/ct/cbpz46s975jgnyggmpymdk4r0000gn/T/apm-install-dir-11587-10718->sdhbei/node_modules/markdown-preview-plus/node_modules/pathwatcher-without-runas
>> node-gyp rebuild
>
> > CXX(target) Release/obj.target/pathwatcher/src/main.o
 >> CXX(target) Release/obj.target/pathwatcher/src/common.o
 >> CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
 >> CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_mac.o
 >> SOLINK_MODULE(target) Release/pathwatcher.node
>
>> fsevents@0.3.8 install /private/var/folders/ct/cbpz46s975jgnyggmpymdk4r0000gn/T/apm-install-dir->11587-10718-sdhbei/node_modules/markdown-preview-plus/node_modules/markdown-it->math/node_modules/ascii2mathml/node_modules/babel/node_modules/chokidar/node_modules/fsevent>s
>> node-gyp rebuild
>
 > SOLINK_MODULE(target) Release/.node
>
>> oniguruma@4.2.2 install /private/var/folders/ct/cbpz46s975jgnyggmpymdk4r0000gn/T/apm-install-dir->11587-10718-sdhbei/node_modules/markdown-preview->plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
>> node-gyp rebuild
>
>  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
>  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
>  LIBTOOL-STATIC Release/oniguruma.a
>  CXX(target) Release/obj.target/onig_scanner/src/onig-cache.o
>  CXX(target) Release/obj.target/onig_scanner/src/onig-result.o
>  CXX(target) Release/obj.target/onig_scanner/src/onig-reg-exp.o
>  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner.o
>  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner-worker.o
>  CXX(target) Release/obj.target/onig_scanner/src/onig-searcher.o
>  CXX(target) Release/obj.target/onig_scanner/src/onig-string-context.o
>  CXX(target) Release/obj.target/onig_scanner/src/unicode-utils-posix.o
>  SOLINK_MODULE(target) Release/onig_scanner.node
>
>npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
>npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
>ld: library not found for -lgcc_s.10.5
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>make: *** [Release/pathwatcher.node] Error 1
>gyp ERR! build error 
>gyp ERR! stack Error: `make` failed with exit code: 2
>gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node->gyp/lib/build.js:269:23)
>gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
>gyp ERR! System Darwin 14.5.0
>gyp ERR! command "node" >"/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node->gyp/bin/node-gyp.js" "rebuild"
>gyp ERR! cwd /private/var/folders/ct/cbpz46s975jgnyggmpymdk4r0000gn/T/apm-install-dir-11587->10718-sdhbei/node_modules/markdown-preview-plus/node_modules/pathwatcher-without-runas
>gyp ERR! node -v v0.10.40
>gyp ERR! node-gyp -v v2.0.2
>gyp ERR! not ok 
>ld: library not found for -lgcc_s.10.5
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>make: *** [Release/.node] Error 1
>gyp ERR! build error 
>gyp ERR! stack Error: `make` failed with exit code: 2
>gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node->gyp/lib/build.js:269:23)
>gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
>gyp ERR! System Darwin 14.5.0
>gyp ERR! command "node" >"/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node->gyp/bin/node-gyp.js" "rebuild"
>gyp ERR! cwd /private/var/folders/ct/cbpz46s975jgnyggmpymdk4r0000gn/T/apm-install-dir-11587->10718-sdhbei/node_modules/markdown-preview-plus/node_modules/markdown-it->math/node_modules/ascii2mathml/node_modules/babel/node_modules/chokidar/node_modules/fsevent>s
>gyp ERR! node -v v0.10.40
>gyp ERR! node-gyp -v v2.0.2
>gyp ERR! not ok 
>npm WARN optional dep failed, continuing fsevents@0.3.8
>npm ERR! Darwin 14.5.0
>npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" >"/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "-->globalconfig" "/Users/IgorDiniz/.atom/.apm/.apmrc" "--userconfig" "/Users/IgorDiniz/.atom/.apmrc" >"install" "/private/var/folders/ct/cbpz46s975jgnyggmpymdk4r0000gn/T/d-11587-10718->girj5o/package.tgz" "--target=0.22.0" "--arch=x64"
>npm ERR! node v0.10.40
>npm ERR! npm  v2.13.3
>npm ERR! code ELIFECYCLE
>
>npm ERR! pathwatcher-without-runas@4.5.0 install: `node-gyp rebuild`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the pathwatcher-without-runas@4.5.0 install script 'node-gyp rebuild'.
>npm ERR! This is most likely a problem with the pathwatcher-without-runas package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node-gyp rebuild
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls pathwatcher-without-runas
>npm ERR! There is likely additional logging output above.
>
>npm ERR! Please include the following file with any support request:
>npm ERR!     /private/var/folders/ct/cbpz46s975jgnyggmpymdk4r0000gn/T/apm-install-dir-11587-10718->sdhbei/npm-debug.log

**Comment by leipert** [comment]
Could you paste `apm check --install`?

How did you install atom?

**Comment by Galadirith** [comment]
Thanks @Arengorn :D

As @leipert said running that command will check you've got the right installation tools.

Looking at the installation problems on you main OSX machine, the errors look practically identical to #90, the issue there was an incompatible version of Xcode. If your running a beta version of OS X then you'll only be able to get the correct version of Xcode if you are a developer. If your not running a beta version of OS X then you'll need to install it [as described by `node-gyp`](https://github.com/nodejs/node-gyp#installation).

On your Ubuntu VM, as it looks like you were able to successfully install MPP the only problem I can think of right now is that you were running an outdated version of Atom. If you can update it that would be great, but I will try to do some investigation on a Ubuntu VM myself. If you could let us know which version of Ubuntu you are running that would be really helpful.

**Comment by Arengorn** [comment]
@leipert Ehm this is weird...
>apm check --install
>Unrecognized command: check
If I recall I installed atom through clicking the "Download for Mac" button at atom.io's homepage; definitely nothing fancy.
@Galadirith 
I'm running the CS50 Appliance (https://manual.cs50.net/appliance/2014/) a modded-ish version of what I think is actually Lubuntu. Also, I've checked #90 and it looks like it's the same, yeah. I'll try rolling Xcode 7 B6 and check if it runs, bloody Apple software...

**Comment by Galadirith** [comment]
@Arengorn Ah woops sorry, the command and flag should have been the other way around:

```bash
apm install --check
```

> I'm running the CS50 Appliance

Thats great thanks for letting me know :D I'll hopefully be able to test that out tomorrow :D Thanks @Arengorn

**Comment by Galadirith** [comment]
@Arengorn Thanks so much for you patience on this :D I'm sorry that I haven't had the time to check out installing against your VM yet, but in the mean time if you need to get it working quickly you could try out our latest bleeding edge code. But if your happy to wait until tomorrow we'll be pushing a new release out that should solve your VM issue and your OS X issue :D

**Comment by leipert** [comment]
@Arengorn  I just pushed a new version (`2.1.0`) of MPP. Could you try installing it?

The new version removes all dependencies that needed compilation, like the pathwatcher-without-runas package in your case. 

I hope installation works flawlessly for you now.

**Comment by Arengorn** [comment]
@Galadirith @leipert Sorry for the late answer, just tested on both OSX and Ubuntu and it works! Thanks so much guys, now I can write my papers in peace! :smile:
If either of you ever drop by Rio remind me to buy you some coffee!

**Comment by Galadirith** [comment]
@Arengorn Thanks so much for letting us know. @leipert worked really hard to eliminate our reliance on dependencies that need compiling, so I'm really glad its working for you. Have fun using MPP and please always feel free to ping us with any issues :D
