### ISSUE TITLE
Error on markdown-preview-plus:toggle and markdown-preview-plus:toggle-render-latex with pandoc backend

### ISSUE THREAD

**Issue by lierdakil** [Galadirith/markdown-preview-plus#104]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5-a76d7a6
**System**: "Gentoo Base
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package, v2.0.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/livid/.atom/packages/markdown-preview-plus/lib/update-preview.coffee:73

TypeError: undefined is not a function
  at prepareCodeBlocksForAtomEditors (/home/livid/.atom/packages/markdown-preview-plus/lib/update-preview.coffee:73:3)
  at UpdatePreview.module.exports.UpdatePreview.update (/home/livid/.atom/packages/markdown-preview-plus/lib/update-preview.coffee:37:5)
  at /home/livid/.atom/packages/markdown-preview-plus/lib/markdown-preview-view.coffee:186:26
  at /home/livid/.atom/packages/markdown-preview-plus/lib/renderer.coffee:36:5
  at Function.callbackFunction (/home/livid/.atom/packages/markdown-preview-plus/lib/renderer.coffee:55:5)
  at handleResponse (/home/livid/.atom/packages/markdown-preview-plus/lib/pandoc-helper.coffee:133:19)
  at ChildProcess.<anonymous> (/home/livid/.atom/packages/markdown-preview-plus/node_modules/pdc/pdc.js:65:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -1:55 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -1:54.9.0 core:close (atom-text-editor.editor.is-focused)
     -1:52.5.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -1:51.8.0 core:close (atom-text-editor.editor.is-focused)
     -1:49.5.0 linter:expand-multiline-messages (atom-text-editor.editor.is-focused)
     -1:49.2.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
     -1:46.8.0 linter:expand-multiline-messages (atom-text-editor.editor.is-focused)
     -1:46.1.0 markdown-preview-plus:toggle-render-latex (atom-text-editor.editor.is-focused)
     -1:22.2.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:20.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:17.2.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -1:16.8.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -1:14.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.4.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:31.3.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
  5x -0:30.4.0 markdown-preview-plus:toggle-render-latex (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-lint",
      "haskell-hindent",
      "autocomplete",
      "linter-hlint",
      "language-pfm",
      "markdown-preview",
      "markdown-preview-pandoc"
    ]
  },
  "markdown-preview-plus": {
    "enableLatexRenderingByDefault": true,
    "enablePandoc": true,
    "pandocArguments": [
      "--filter=pandoc-crossref",
      "--smart"
    ],
    "pandocMarkdownFlavor": "markdown"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.5
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
browser-plus, v0.0.34
build, v0.45.0
haskell-ghc-mod, v0.8.14
haskell-pointfree, v0.1.2
ide-haskell-cabal, v0.0.0
language-dot, v1.6.0
language-haskell, v1.4.1
language-latex, v0.6.1
linter, v1.5.0
linter-coffeelint, v1.0.2
linter-pylint, v1.0.0
markdown-preview-plus, v2.0.2
markdown-table-formatter, v2.5.3
minimap, v4.13.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
wordcount, v2.3.0
zotero-bibtex-autocomplete, v0.0.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
And a quick fix:
in `lib/markdown-preview-view.coffee` add
`document.createRange().createContextualFragment \` at line 187.

**Comment by Galadirith** [comment]
@lierdakil Thanks so much for catching this issue and providing a solution, I really appreciate that. We'll make sure this is patched in the next release :D

While there should of course be no use case that leads to this bug, could I ask why you are trying to enable maths rendering without having installed `mathjax-wrapper`.

Thanks again @lierdakil

**Comment by lierdakil** [comment]
Well, reason being, I didn't pay enough attention to README, so I tried to run without mathjax-wrapper :laughing:  This of course doesn't normally happen if mathjax-wrapper is available.

That said, this code path can get executed even if mathjax-wrapper is installed. In particular, when restarting Atom with preview pane open, there is a race condition related to package initialization order: if markdown-preview-plus is initialized *before* mathjax-wrapper, I do get "mathjax-wrapper not installed" message (or this error, without fix applied).

Anyway, why did you choose to distribute mathjax-wrapper as Atom package? Wouldn't it make more sense to package it as npm module? That would make it much easier to depend on it, no?

**Comment by leipert** [comment]
The problem:

As an npm package it would be needed to be installed every time there is an update (at least I believe so). But it seems like there is a npm package for atom package dependencies:

https://github.com/AtomLinter/linter-markdown/issues/6

Maybe we find a fix for that race condition.

On another note, if I recall correctly, you are the maintainer of markdown-preview-pandoc. Thanks for that, as I let me inspire by your code prior to the contribution to this package. Do you have any other ideas for mpp?

**Comment by lierdakil** [comment]
@leipert, well, I actually do, but that's a problem that I didn't solve satisfactory with markdown-preview-pandoc... Long story short, I'd very much like if preview auto-scrolled to at least somewhere around cursor position. Best I could do was to scroll preview window to the same percentage, which didn't always turn out that good... I can open an issue if you want me to.

FYI, I recently deprecated markdown-preview-pandoc in favor of markdown-preview-plus, since all functionality I wanted and more is actually implemented here. So thanks for that :)

**Comment by Galadirith** [comment]
@lierdakil awesome stuff :D 

> I tried to run without mathjax-wrapper 

So I did code it to not preview without `mathjax-wrapper` installed if your rendering equations, but really that restriction doesn't have to be there. In particular I noticed your [texsvg.hs](https://gist.github.com/lierdakil/6a95278d02256a74a0fc); a user using their own maths renderer could definitely be part of MPP, would that be something you would like?

>Anyway, why did you choose to distribute mathjax-wrapper as Atom package? 

So way back at the beginning of MPP I didn't really know that much about MathJax and it was a rather >50MB install which I did realised after a few releases I could not force on users every time (as @leipert said). But as I've learned for our purposes it can be shrunk massively to <2MB. Ultimately I want to remove the dependency on `mathjax-wrapper` which I hope to do with [`magnetite`](https://github.com/Galadirith/magnetite). If you feel adventurous you can read more about my plans at Galadirith/mathjax-wrapper#1

> Best I could do was to scroll preview window to the same percentage, which didn't always turn out that good... I can open an issue if you want me to.

So we've now got on demand sync #80 when using our default parser `markdown-it`. While not disabled for Pandoc rendering it doesn't really work well with it. So really we've got 4 problems:

- On demand sync for `markdown-it` (which is done :D)
- Auto sync for `markdown-it`
- On demand sync for Pandoc
- Auto sync for Pandoc

Please do open up an issue for Pandoc syncing, we've already got #9 that I will re-designate as `markdown-it` sync. I would love to hear your ideas on Pandoc syncing. With `markdown-it` we are fortunate because we have source mapping (no % scrolling :D) but the best that exists for Pandoc seems to be the `--trace` option that I have yet to properly analysis.

>  In particular, when restarting Atom with preview pane open

Ah thanks for spotting that use case. I know that MPP is not deserializing well and I really want to get that fixed :D 

Thanks again @lierdakil

**Comment by lierdakil** [comment]
>  a user using their own maths renderer could definitely be part of MPP, would that be something you would like?

I don't really think it's necessary. `texsvg.hs` was just an easy way to get math to work, and I think that mathjax does a better job here (it looks prettier, for one). When user filters are absolutely necessary, it's already possible to pass options to pandoc, including filters, so I think it's pretty much covered here. Theoretically, it should be possible to use service-hub plugin system to swap mathjax renderer for something else, but I really doubt it's worth it.

> Auto sync for `markdown-it`

This should be really easy. Just binding a relevant call to `TextEditor.onDidChangeCursorPosition` should do it. Option and a toggle command would be a nice bonus.

> sync for Pandoc

Opened an issue, referenced above. This will be a tad more challenging.

**Comment by Galadirith** [comment]
> I don't really think it's necessary.

Thats cool, thanks for your thoughts :D

> This should be really easy. Just binding a relevant call to `TextEditor.onDidChangeCursorPosition`

So definitely a possibility. However there would be a couple of issues with this. One would be how computationally expensive it would be to call the sync methods. There would most likely have to be some debouncing somewhere in that pipeline which may or may not give an undesirable effect. Second is that the sync is discontinuous for example blank lines in the source map to nothing in the preview. But the hard part was always the on demand bit :D

**Comment by Galadirith** [comment]
@lierdakil Out of curiosity did you add any error catching to the code? The default behaviour I get if I don't add error catching when I try to generate this error is simply a dev tools error without stacktrace.

**Comment by lierdakil** [comment]
My guess is that this would probably be because you're testing with
markdown-it backend? With markdown-it, I get promise failed error in
console, with no trace. Not sure if I got trace on Atom reload though.
7 сент. 2015 г. 13:45 пользователь "Edward Fauchon-Jones" <
notifications@github.com> написал:

**Comment by Galadirith** [comment]
Thanks @lierdakil

**Comment by leipert** [comment]
nice one!
