### ISSUE TITLE
Error Installing Package

### ISSUE THREAD

**Issue by CalculusWarrior** [Galadirith/markdown-preview-plus#105]
Whenever I attempt to install this package, it drops the following error. This has happened on two separate computers, running Windows 7 and 10, and I've attempted installing both from the GUI and command line.

    npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
    npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
    npm WARN optional dep failed, continuing fsevents@0.3.8
    gypgypnpm ERR! Windows_NT 6.2.9200
    npm ERR! argv "C:\\Users\\Bryan\\AppData\\Local\\atom\\app-1.0.11\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Bryan\\AppData\\Local\\atom\\app-1.0.11\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Bryan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Bryan\\.atom\\.apmrc" "install" "C:\\Users\\Bryan\\AppData\\Local\\Temp\\d-11586-6100-gogun6\\package.tgz" "--target=0.22.0" "--arch=ia32"
    npm ERR! node v0.10.40
    npm ERR! npm  v2.13.3
    npm ERR! code ELIFECYCLE

    npm ERR! oniguruma@4.2.2 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the oniguruma@4.2.2 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the oniguruma package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls oniguruma
    npm ERR! There is likely additional logging output above.

**Comment by Galadirith** [comment]
@CalculusWarrior Thanks so much for checking out MPP and I'm really sorry your having installation problems. We have a document [win-install](https://github.com/Galadirith/markdown-preview-plus/blob/2c37fae5893be17238d24671b3682e3dd83a046d/docs/win-install.md) that goes through some common problems with installing MPP on Windows. What would be incredibly helpful is if you could have a read of that and try the solutions suggested there.

A quick check you can also do is run `apm install --check` which checks to see if you have the tools needed to install MPP.

Thanks @CalculusWarrior, hopefully we can get this sorted quickly for you and please post back with any questions or results :D

**Comment by leipert** [comment]
@CalculusWarrior I just pushed a new version (`2.1.0`) of MPP. Could you try installing it?

The new version removes all dependencies that needed compilation, like the oniguruma package in your case. 

I hope installation works flawlessly for you now.

**Comment by CalculusWarrior** [comment]
Ah, excellent, it must have been a dependency issue then as it now installs perfectly! Thanks so much for the help!

**Comment by leipert** [comment]
No Problem, thanks for trying it out ;)
