### ISSUE TITLE
Toggle not closing preview

### ISSUE THREAD

**Issue by sim642** [Galadirith/markdown-preview-plus#110]
I just updated markdown-preview-plus to 2.1.0 and found out that pressing `ctrl-shift-M` to toggle the preview opens it properly but does not correctly close it again. Pressing that key combo momentarily seems to close it but immediately opens again, judging by the flicker it causes.

**Comment by Galadirith** [comment]
@sim642 I'm really sorry your having a problem with our latest release. Could you please post back with a few details:

- Your Atom version
- Your OS
- The output of `apm list -i`

I'm afraid I haven't been able to replicate the bug following the steps you've posted, but hopefully we can find the source of the issue quickly. Thanks @sim642

**Comment by sim642** [comment]
* Atom: 1.0.10
* OS: Xubuntu 15.04
* `apm list -i`: 
```
focus-light@1.1.0
language-latex@0.6.1
markdown-preview-plus@2.1.0
mathjax-wrapper@0.1.0
minimap@4.13.3
minimap-find-and-replace@4.3.0
minimap-git-diff@4.1.8
minimap-selection@4.3.0
term2@0.9.20
```

**Comment by sim642** [comment]
It seems that after updating the package from inside Atom, the keybinds somehow got appended (as shown by the command palette). Restarting Atom fixed the issue.

**Comment by Galadirith** [comment]
@sim642 That's great I'm glad its working correctly now. Thanks @sim642
