### ISSUE TITLE
Citations don't work for YAML embedded references?

### ISSUE THREAD

**Issue by vsivsi** [Galadirith/markdown-preview-plus#111]
I've enabled pandoc and citations support and disabled "Remove references", but the following document doesn't appear to have any citations processing done on it.  Running it through pandoc manually as `pandoc --filter pandoc-citeproc -fmarkdown -thtml -o test.html Citations.md` works fine.

```markdown
---
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for deoxyribose
    nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: http://www.nature.com/nature/journal/v171/n4356/abs/171737a0.html
  language: en-GB
...

### Header

So now I'm going to cite that paper [@WatsonCrick1953].

And then @WatsonCrick1953 said something else.

Also Watson and Crick revealed the structure [@WatsonCrick1953 fig. 2].

#### References cited

```

Any ideas?

**Comment by leipert** [comment]
Yeah, I just tested it. The wrapper around pandoc searches for a external bib file and only if it find's one, it will enable the citation rendering. This is most certainly a bug :+1: 

However there is a quick fix for you: Simply add `--filter=pandoc-citeproc` to `Pandoc Options: Commandline arguments`

**Comment by leipert** [comment]
@vsivsi It is fixed and will be out in the wild in the next version sometime.
Until then please use the fix mentioned above.

Thanks for using mpp and your report.

**Comment by vsivsi** [comment]
Great. The workaround above works, so long as I use the full path to my copy of `pandoc-citeproc`.

Thanks for the super-fast response!
