### ISSUE TITLE
Could the preview automatically scroll to the changed section of source file?

### ISSUE THREAD

**Issue by theoctopod** [Galadirith/markdown-preview-plus#116]
When editing parts of a source file that happens to be off-screen in the preview, the preview tends not to scroll to that edited part. 

Being on a laptop, it would be convenient if the preview could automatically scroll to the part that changed as to not have to scroll it myself every time it updates.

Is this kind of thing possible?

**Comment by theoctopod** [comment]
Sorry, didn't see https://github.com/Galadirith/markdown-preview-plus/issues/106. Gonna close this now.

**Comment by Galadirith** [comment]
No problem @theoctopod :D

You may already know the this but just to summarize the different types of syncronization:

1. On demand sync
2. Automatic scroll sync
3. On demand sync when Pandoc is enabled
4. Automatic scroll sync when Pandoc is enabled

We already have added (1) to MPP and you can read about it [here](https://github.com/Galadirith/markdown-preview-plus/blob/34a05c1a1eb204e89747dd7e4b2113f20a35b6c0/docs/features.md) under the last bullet point **On demand synchronization**. This also partially works when Pandoc is enabled. #106 is to work towards automatic scroll synchronization when Pandoc is enabled, but were also investigating automatic scroll synchronization when it is not enabled.

Hopefully that makes sense, please post back if you had any questions :D

Thanks @theoctopod
