### ISSUE TITLE
Incompatible with Atom 1.0.13?

### ISSUE THREAD

**Issue by szhorvat** [Galadirith/markdown-preview-plus#118]
Today after updating Atom to 1.0.13, it told me that 

> Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

The rebuild failed due to a missing command.

```
/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/szhorvat/.atom/.apm/.apmrc" "--userconfig" "/Users/szhorvat/.atom/.apmrc" "rebuild" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fsevents@0.3.8 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fsevents@0.3.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/szhorvat/.atom/packages/markdown-preview-plus/npm-debug.log
```

**Comment by leipert** [comment]
@szhorvat Which MPP Version `2.1.0`?
Could you paste `/Users/szhorvat/.atom/packages/markdown-preview-plus/npm-debug.log`?
I suppose you are on OSX. I just updated to `1.0.13` and everything worked fine...

**Comment by szhorvat** [comment]
Here you go: https://gist.github.com/szhorvat/21992753294df0289bdd

**Comment by szhorvat** [comment]
Before posting here, I did try uninstalling the package, restarting Atom, and reinstalling it. It did not help.  Do you think something is broken in my Atom configuration?  Is there anything I can try to fix it short of deleting all of `/.atom`?

**Comment by leipert** [comment]
Nope, it is some problem with one of our dependencies dependencies dependencies:
https://gist.github.com/szhorvat/21992753294df0289bdd#file-npm-debug-log-L3149.

I will go on a trip to fixville and try to figure this out!

**Comment by leipert** [comment]
We are working on it. Sorry I have no solution for you yet, maybe it helps you that this issue should be mac specific.

**Comment by leipert** [comment]
Maybe try:
```bash
cd /Users/szhorvat/.atom/packages/markdown-preview-plus/node_modules/markdown-it-math/node_modules/ascii2mathml/node_modules/babel/node_modules/chokidar/
rm -rf node_modules
npm install --no-optional
```

**Comment by leipert** [comment]
I get the same error now. Hopefully I can push a quick fix soon :+1: 
![screen shot 2015-09-18 at 14 40 29](https://cloud.githubusercontent.com/assets/2906107/9959326/53883e1a-5e13-11e5-932d-442fe53ebd09.png)

**Comment by leipert** [comment]
@szhorvat I pushed `2.1.1` which fixes the problem with a quickfix.
I am leaving this issue open anyhow, so that we can work out a more sustainable fix.

**Comment by szhorvat** [comment]
Thank you Lukas! The preview works again.

**Comment by leipert** [comment]
Seems to be related to https://github.com/atom/atom/issues/8837.#

I am closing this issue, as atom should work now properly again.
