### ISSUE TITLE
latex rendering not working

### ISSUE THREAD

**Issue by dougcoates** [Galadirith/markdown-preview-plus#12]
I have installed the markdown preview plus package and it is not displaying rendered latex, I have tried reinstalling the package and updating it in the way suggested in the troubleshooting guide  with no success.

**Comment by Galadirith** [comment]
@dougcoates I'm really sorry your having a problem with the package. So I have a few questions and things you can try to get LaTeX to render, and hopefully one will fix it for you :D I apologise if some of them seem obvious. 

If you are able to could you download this markdown file [test-file-mpp.md](https://gist.githubusercontent.com/Galadirith/2db3077b45c699667c89/raw/519a233abb4c53a6077de0221128dc104f42c5ba/test-file-mpp.md) and use that for testing. What ever file you use shouldn't make a difference, but at least this way I can be certain its a file I know works.

- Can I first ask what you do see when you open a preview tab with `ctrl-shift-m`; is it blank, does a tab even open?
- Have you actually toggled LaTeX rendering? Once you have opened a preview tab (thats what `ctrl-shift-m` does) then you still need to then toggle LaTeX rendering with `ctrl-shift-x`. Please have a read of [LATEX](https://github.com/Galadirith/markdown-preview-plus/blob/d96e3ec321829f38548ac99cb81aea80cc0fe759/LATEX.md) which will give you some more information.
- Have you disabled the built in markdown-preview package as detailed in the [Installation Instructions](https://github.com/Galadirith/markdown-preview-plus/tree/d96e3ec321829f38548ac99cb81aea80cc0fe759#installation-instructions)

If you have done all those things then what would be really useful to help you diagnose the problem would be any error output from atom (press `ctrl-alt-I` in atom, click the `Console` tab and either paste a screenshot or paste the output to this issue). What would also be useful to know is the operating system you are currently using.

Please let me know how everything goes, and of course please post back with any questions you may have :D

**Comment by dougcoates** [comment]
Thanks for your quick response!

To answer your questions:

 - With the the test file, latex still does not render
 - The default markdown package is disabled
 - When pressing `ctrl-shift-m` the preview window appears and displays the rendered markdown correctly. Latex math in `$` just shows as normal text.
 - Pressing `ctrl-shift-x` has no effect nor does toggling latex rendering from the command menu
 - I am running Arch linux with kernel 3.10
 - The log window gives no output what so ever!

Not sure what else I can do to diagnose he problem, please let me know if you need anything else.

**Comment by dougcoates** [comment]
Sorry pressed the close button by accident...

**Comment by Galadirith** [comment]
Thanks for all the information @dougcoates really useful stuff. I'm downloading an Arch Linux image right now and I'll see what happens in a virtualbox. However what you described doesn't sound like an Arch Linux issue. I'm gonna have a dig around and see what I can find, and I'll update you as soon as I can :D

**Comment by dougcoates** [comment]
That's great! Thanks for your speedy response!

**Comment by Galadirith** [comment]
@dougcoates I've just push out a new version `1.0.1` which is now compatible with the most recent version of Atom `0.169.0`, and hopefully should work for you. Just search for **Markdown Preview Plus** in **File &rsaquo; Settings &rsaquo; Packages** and click update :D. You will need to upgrade to that latest version if you haven't already (Atom should have done that automatically for you :D).

Note that their is one additional step in the [Installation Instructions](https://github.com/Galadirith/markdown-preview-plus/blob/dcb9132cd19352b105a1e3963cd01a847e0f8549/README.md#installation-instructions), which means it takes a little longer to install, but means that future updates should be much quicker to install (<2mins) and I should finally be able to start pushing out requested features :D 

Please let me know if everything works for you, and as always please post back with any problems :D

**Comment by dougcoates** [comment]
Just updated to the newest version and everything is working great. Thanks!

**Comment by masszhou** [comment]
I met the similar problem, then I solved my problem by disable the default markdown preview plugin from atom.
