### ISSUE TITLE
MathJax-Wrapper not detected

### ISSUE THREAD

**Issue by Aeon512** [Galadirith/markdown-preview-plus#124]
Hi,

I just installed the latest atom version (as the zip version) and installed markdown-preview-plus, markdown-preview-plus-opener and mathjax-wrapper via the settings menu. I then configured the settings to display math automatically.

With every restart afterwards (while a markdown document is opened) I get the error message that I apparently want to display maths but the necessary mathjax-wrapper is not installed.

However, if i check the .atom directory the mathjax-wrapper directory is present.
Is there any log to see what's going wrong?

I'm on windows 8.

Thanks a lot

**Comment by Aeon512** [comment]
Apparently it is necessary to restart the OS before mathjax-wrapper starts working...
Sorry for the noise

**Comment by Galadirith** [comment]
Thanks @Aeon512. Thats no problem at and I'm glad you've got it working, although I didn't realize myself a restart was necessary. 

In case your issues do reappear, they may be related to a race condition bug that was discussed in https://github.com/Galadirith/markdown-preview-plus/issues/104#issuecomment-138086564. I have fixed this and will be publishing it tomorrow. Thanks again @Aeon512.

**Comment by Aeon512** [comment]
@Galadirith Actually, with using it more and more it is actually a race condition forced by the mathdown-preview-plus-opener plugin. If the problem occurs, I have to close the preview and trigger it manually using the keyboard shortcut, and everything works

**Comment by Galadirith** [comment]
@Aeon512 Ok great thanks for letting me know, the release should fix this.

**Comment by Galadirith** [comment]
@Aeon512 Just to let know I just publish `2.3.0` which should now fix the race conditions causing your errors. While all our internal tests are passing, I haven't tested it with `markdown-preview-plus-opener` so please let me know if the issue is still there. Thanks @Aeon512.

**Comment by Aeon512** [comment]
@Galadirith Tested and works. The problem no longer occurs.Thanks a lot @Galadirith

**Comment by Galadirith** [comment]
Great, thanks for letting me know @Aeon512.
