### ISSUE TITLE
Enter/return key breaks upon opening the preview pane

### ISSUE THREAD

**Issue by olmokramer** [Galadirith/markdown-preview-plus#13]
When I open the preview pane, the enter key stops responding in the editor. When I close the file and open it again the enter key responds again.

**Comment by Galadirith** [comment]
@olmokramer thanks for checking out my package and i'm really sorry your having some issues with it. 

So I have a few questions that I would like to ask you:

1. First do any other keys stop responding when you open the preview pane? 
2. Which versions of Atom and markdown-preview-plus do you currently have installed? If your not already running `v0.169.0` of atom and `v1.0.1` of MPP could you update to both of them. 
3. Could you also tell me which operating system are you using?
4. When you open a preview pane do you use the keymap `ctrl-shift-m` or the menu option **Packages &rsaquo; Markdown Preview Plus &rsaquo; Toggle Preview**. Does the return key break if you open a preview pane through both of these methods?
5. Have you installed any other packages to Atom? If you have quite a few installed then the easiest way to get a list would be to open up a terminal and type `apm list -i`. Then you can just copy and paste the list to this issue. 
6. Finally can I ask you to check for any errors that Atom might be throwing out:
   - Open an Atom window and open a preview pane such that the return key is no longer responding.
   - Open up DevTools, which I belive for a mac is with `ctrl-alt-i` or you can click **View &rsaquo; Developer &rsaquo; Toggle Developer Tools**.
   - Click the **Console** tab.
   - Are there any error message? You should only see the message `Window load time: xxxxms`. If there is anything more than that could you copy and paste it to this issue.

I'm sorry for the rather long list of questions, but hopefully we can get your problem resolved quickly. Please post back if you have any problems with anything I've asked :D

**Comment by olmokramer** [comment]
Thanks for the quick reply! Glad I can help :)

To answer your questions:
1. All the other keys still seem to work just fine
2. I'm on Atom `0.169.0` and MPP `1.0.1`
3. OS: Linux Debian (testing)
4. I tried both. Still `enter` does nothing
5. Output of `apm list -i`:
```
olmo@crunchbang:~$ apm list -i
/home/olmo/.atom/packages (71)
├── atom-alignment@0.9.3
├── atom-backbone@0.6.0
├── atom-beautify@0.21.2
├── atom-color-highlight@3.0.3
├── atom-handlebars@0.4.0
├── autocomplete-paths@0.9.1
├── autocomplete-plus@1.1.0
├── autocomplete-snippets@0.3.2
├── bezier-curve-editor@0.6.2
├── change-case@0.4.0
├── coffee-autocompile@0.0.0
├── color-picker@1.2.6
├── dark-flat-syntax@0.2.0
├── dark-flat-ui@0.6.0
├── docblockr@0.5.8
├── editorconfig@0.2.3
├── emmet@2.3.0
├── fancy-new-file@0.7.0
├── file-icons@1.4.4
├── file-types@0.3.0
├── gist-it@0.5.0
├── git-history@1.1.2
├── git-log@0.2.0
├── git-plus@4.3.1
├── git-tab-status@1.3.0
├── hex@0.3.10
├── highlight-selected@0.7.0
├── html-entities@0.2.0
├── isotope-ui@1.0.2
├── language-apache@1.2.0
├── language-jade@0.3.0
├── language-latex@0.4.1
├── language-stylus@0.1.0
├── less-autocompile@0.3.3
├── linter@0.9.1
├── linter-clang@2.9.0
├── linter-coffeelint@0.1.7
├── linter-csslint@0.0.11
├── linter-htmlhint@0.0.8
├── linter-javac@0.1.3
├── linter-jshint@0.1.0
├── linter-jsonlint@0.1.2
├── linter-less@0.3.1
├── linter-php@0.0.11
├── linter-shellcheck@0.0.6
├── linter-xmllint@0.0.5
├── lorem-ipsum@0.3.0
├── markdown-pdf@1.2.11
├── markdown-preview-plus@1.0.1
├── mathjax-wrapper@0.1.0
├── merge-conflicts@1.2.8
├── minimap@3.5.4
├── minimap-color-highlight@3.1.0
├── minimap-find-and-replace@3.1.0
├── minimap-git-diff@3.1.0
├── minimap-highlight-selected@3.1.0
├── minimap-selection@3.1.1
├── preview@0.13.4
├── project-manager@1.14.1
├── regex-railroad-diagram@0.6.3
├── slash-closer@0.7.1
├── sort-lines@0.8.0
├── stacktrace@0.0.1
├── stylus-autocompile@0.0.0
├── terminal-status@1.3.5
├── ti-alloy-related@0.6.0
├── ti-build-atom@0.7.0
├── todo-show@0.6.0
├── travis-ci-status@0.11.1
├── turbo-javascript@0.0.5
└── underscorejs-snippets@0.2.2
```
Although I didn't try to run Atom with just this one package, I tried disabling `markdown-pdf`, the only other package related to markdown. I'll try disabling everything except `markdown-preview-plus` and post back the results
6. No error messages in the console, but this is what's in there:
```
/home/olmo/.atom/packages/emmet/lib/emmet.coffee:115 Loading Emmet extensions from ~/emmet
/home/olmo/.atom/packages/linter-clang/lib/init.coffee:13 activate linter-clang
/home/olmo/.atom/packages/linter-coffeelint/lib/init.coffee:12 activate linter-coffeelint
/home/olmo/.atom/packages/linter-csslint/lib/init.coffee:11 activate linter-csslint
/home/olmo/.atom/packages/linter-htmlhint/lib/init.coffee:11 activate linter-htmlhint
/home/olmo/.atom/packages/linter-javac/lib/init.coffee:7 activate linter-javac
/home/olmo/.atom/packages/linter-jshint/lib/init.coffee:11 activate linter-jshint
/home/olmo/.atom/packages/linter-jsonlint/lib/init.coffee:11 activate linter-jsonlint
/home/olmo/.atom/packages/linter-less/lib/init.coffee:4 activate linter-less
/home/olmo/.atom/packages/linter-php/lib/init.coffee:7 activate linter-php
/home/olmo/.atom/packages/linter-shellcheck/lib/init.coffee:7 activate linter-shellcheck
/home/olmo/.atom/packages/linter-xmllint/lib/init.coffee:7 activate linter-xmllint
index.js:64 Window load time: 1962ms
```

If you need anything else, just ask :)

**Comment by olmokramer** [comment]
Alright... So I tried running Atom with only `markdown-preview-plus` and `mathjax-wrapper` enabled and now my enter key responds again...

Looks like I've got some investigating to do. I'll report back when/if I learn anything :)

**Comment by olmokramer** [comment]
Ok I found the culprit: It is the [emmet](https://atom.io/packages/emmet) package. It adds this keybinding:
```
'.pane .editor:not(.mini)':
  'enter': 'emmet:insert-formatted-line-break-only'
```

So when I preview the markdown, the editor is inside a `.pane`, thus breaking the enter key. I think I'm going to remove Emmet, as lately it's caused me more harm than gain...

Sorry to have bothered you, but I think it's some useful information after all :)

And great job on a very useful package! I loved it before I'd even used it :)

**Comment by Galadirith** [comment]
@olmokramer Im really glad you managed to track down the problem. No bother at all, and yes definitely really useful information to know :D Thanks so much for your kind words and If you have any more problems please do throw them my way :D

**Comment by olmokramer** [comment]
Glad I could help :D
