### ISSUE TITLE
can't support the `#` or `##` to resolve title

### ISSUE THREAD

**Issue by hhqcontinue** [Galadirith/markdown-preview-plus#131]
When using markdown-preview-plus plugin,I found it only support the ======= or ----------- to resolve the title syntax but can't support the # or ## to resolve the title.

**Comment by Galadirith** [comment]
@hhqcontinue Thanks so much for using MPP.

I've been unable to replicate your errors. When I place from 1-6 `#` at the beginning of a line I get a header. I'd be really grateful if you could post an example of a markdown document when headers don't work for you with `#`, preferable as a [gist](https://gist.github.com/).

Thanks @hhqcontinue.

**Comment by hhqcontinue** [comment]
I am sorry.It is my fault that I missing a space between `#` and title, so it can't be rendered.Does is possible to support `#` that without space between title.If it can't,maybe I should close this issue.

**Comment by Galadirith** [comment]
@hhqcontinue absolutely. In fact we already added support for this in #96 after a discussion in #88. In fact it's an option that should already be enabled by default. But it seems it's not for you, so simply go to MPP's settings page in Atom and enable **Use Lazy Headers**.

Thanks @hhqcontinue, please let me know how that goes.

**Comment by hhqcontinue** [comment]
@Galadirith I have read your solution but I can't found `Use Lazy Headers` in MMP's settings page.

**Comment by Galadirith** [comment]
Thanks @hhqcontinue that's interesting. What would be really useful is if you could send me a list of all the plugins that you have installed and their associated versions. You can do this by running the command `apm list --installed` from a console. Thanks @hhqcontinue.

**Comment by hhqcontinue** [comment]
It is weird that it shows empty is the console.

**Comment by Galadirith** [comment]
Ok thanks @hhqcontinue. From your description it sounds like you havn't installed any packages. Did you follow our installation instructions which can be found [here](https://github.com/Galadirith/markdown-preview-plus/blob/c75d3109d0bdbd56d984e6c526f88e177fbe9c55/README.md#installation)? 

Thanks again @hhqcontinue.

**Comment by hhqcontinue** [comment]
um.I have installed a lot packages, or I can't tell you that a space between `#` and title.But it show empty weirdly.And I can see package list on graphical interface.I use windows 7 os by the way.Does is matter?

**Comment by hhqcontinue** [comment]
It turns out that atom has installed MPP plugin automatically.
One of my friend use linux os,and the result is as follow:

monkey@localhost:~> apm list --installed
/home/qmonkey/.atom/packages (9)
├── autocomplete-clang@0.8.7
├── clang-format@1.16.0
├── go-plus@3.5.1
├── linter@1.8.1
├── linter-gcc@0.3.8
├── switch-header-source@0.20.0
├── symbols-tree-view@0.10.0
├── sync-settings@0.6.0
└── term2@0.9.21

his os information is

**Comment by hhqcontinue** [comment]
Linux localhost 4.1.6-3-desktop #1 SMP PREEMPT Fri Aug 28 10:59:34 UTC 2015 (d867e86) x86_64 x86_64 x86_64 GNU/Linux

**Comment by hhqcontinue** [comment]
It turns out that atom has installed MPP plugin automatically,and the `apm list --installed` command can not show the package that was installed automatically.
One of my friend use linux os,and he can use the MPP plugin.he run the command,get list as follow:
 apm list --installed
/home/qmonkey/.atom/packages (9)
├── autocomplete-clang@0.8.7
├── clang-format@1.16.0
├── go-plus@3.5.1
├── linter@1.8.1
├── linter-gcc@0.3.8
├── switch-header-source@0.20.0
├── symbols-tree-view@0.10.0
├── sync-settings@0.6.0
└── term2@0.9.21

his os information:
Linux localhost 4.1.6-3-desktop #1 SMP PREEMPT Fri Aug 28 10:59:34 UTC 2015 (d867e86) x86_64 x86_64 x86_64 GNU/Linux

**Comment by leipert** [comment]
Are you sure that MPP is installed automatically and not markdown-preview???

**Comment by Galadirith** [comment]
@hhqcontinue thanks again for your reply. Just to follow up on what @leipert said, I would be incredibly surprised if MPP is installed automatically. Just to be clear, our package `markdown-preview-plus` is different from the default markdown package (that comes included with Atom) [`markdown-preview`](https://atom.io/packages/markdown-preview). Thanks @hhqcontinue.

**Comment by hhqcontinue** [comment]
@Galadirith Sorry to reply you so late.Yes, it is markdown plugin that atom installed autonatically.It's my fault to mistake this.
But I still can't get anything by running `apm list --installed`

**Comment by leipert** [comment]
As @Galadirith said, this package is not installed with Atom automatically. To report an issue with the automatic installed package [`markdown-preview`](https://atom.io/packages/markdown-preview), you can do that here:
https://github.com/atom/markdown-preview/issues

You can try markdown-preview-plus, which supports rendering headers correctly.

To install markdown-preview-plus, just do the following:

![](http://g.recordit.co/n0U8fX2soo.gif)

and disable the preinstalled markdown-preview package:

![](http://g.recordit.co/ERn70tiGEM.gif)

I will close this issue, feel free to reopen it, if you have further questions.
