### ISSUE TITLE
Scroll with content

### ISSUE THREAD

**Issue by ramvi** [Galadirith/markdown-preview-plus#133]
It would be great if there was an option for connecting the source and the preview view, so that if you scoll in one window the other one follows

**Comment by Galadirith** [comment]
Thanks @ramvi I really appreciate your input. This is definitely a feature were working on, although at this point in time I can't give you any estimate on when it might be released.

I'm going to close this in favour of #9 which brings together the discussion on this. But if you do have any further comments on this feature then please do post to #9. Thanks again @ramvi.
