### ISSUE TITLE
list-style-type somehow unsupported

### ISSUE THREAD

**Issue by dmckean** [Galadirith/markdown-preview-plus#135]
I've been using the `fancy_lists` extension in pandoc to generate A., B., C.-style orders lists in HTML from Markdown. The pandoc generator correctly writes the `list-style-type: upper-alpha` in the `ol` HTML tag, but the preview window fails to render the `li` elements with upper-roman markers.

ex.

file.md

    ---
    title: "My List of Ordered Things"
    output:
      html_document:
        md_extensions: +fancy_lists
    ---
    A.  First
    B.  Second
    C.  Third

Renders in markdown-preview-plus as

1. First
2. Second
3. Third

file.html
```html
     . . .
    <body class='markdown-preview'>
      <ol style="list-style-type: upper-alpha">
        <li>First</li>
        <li>Second</li>
        <li>Third</li>
      </ol>
    </body>
```

**Comment by leipert** [comment]
Thanks for your Report, @dmckean. It is fixed and pushed.
