### ISSUE TITLE
Updating to “markdown-preview-plus@2.2.2” failed

### ISSUE THREAD

**Issue by ivomarsan** [Galadirith/markdown-preview-plus#140]
```EACCES, unlink '/home/ivomarsan/.atom/packages/markdown-preview-plus/.coffeelintignore'```
Help!

**Comment by Galadirith** [comment]
@ivomarsan I really apologise I wasn't able to reply to you sooner. Have you been able to update to `v2.2.2` since posting the issue? If not are you still getting the same error?

**Comment by ivomarsan** [comment]
Yeah @Galadirith , I use the `v2.2.2` now :smiley: thanks!

**Comment by Galadirith** [comment]
@ivomarsan Thats great I'm really glad, thanks for letting me know. Please let us know if you have any issues in the future.
