### ISSUE TITLE
LaTeX  not rendering, then issues with uninstalling

### ISSUE THREAD

**Issue by Tinkerer-** [Galadirith/markdown-preview-plus#141]
I had an issue with Markdown Preview Plus  where it was not rendering the math anymore (also not with pandoc selected!). I thought it might be good to uninstall the package and re-install, but then I got this notification:

`Uninstalling “markdown-preview-plus” failed.Hide output…
Failed to delete markdown-preview-plus: ENOTEMPTY, directory not empty 'C:\Users\SluiterVIJ\.atom\packages\markdown-preview-plus\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\src\manipulation'`

Deleting the markdown-preview-plus folder and then reinstalling solved the issue, but still wanted to let you know. Thanks for the package!

**Comment by leipert** [comment]
It seems like the uninstall routine might not have run correctly. Could you try

1. uninstalling MPP
2. Checking that the folder `C:\Users\SluiterVIJ\.atom\packages\markdown-preview-plus` does not exist. (Optionally deleting it?)
3. installing MPP

**Comment by Galadirith** [comment]
Thanks @Tinkerer-. Following up on what @leipert, have you experienced any issues since reinstalling MPP? Thanks for raising the issue, I will run some uninstall tests before our next release. Thanks again @Tinkerer-.

**Comment by Tinkerer-** [comment]
*cough* the issue with no LaTeX was that I still had Markdown Preview installed, and that was being run instead of Markdown Preview Plus. By disabling Markdown Preview, and reinstalling Markdown Preview Plus (by removing the complete folder in the packages directory, and then reinstalling the usual way from the Atom settings panel) everything works like  a charm again.

**Comment by Galadirith** [comment]
Thanks for the update @Tinkerer-, and we've all been there :smile:. As always please let us know if you have any issues in the future.
