### ISSUE TITLE
picture

### ISSUE THREAD

**Issue by durianskh** [Galadirith/markdown-preview-plus#145]
can not show picture in the preview file and converted html file

**Comment by Galadirith** [comment]
@durianskh Thanks for opening the issue. In my tests pictures in the preview are working fine. Could you please provide an example document in which your experiencing this issue. Thanks @durianskh.

**Comment by Galadirith** [comment]
@durianskh As its been several months without a reply I will close this issue. However if you are still having any problems related to this issue then please feel free to post back to this thread. Thanks again @durianskh
