### ISSUE TITLE
Use the 'atom-text-editor' instead of the 'editor-colors' class

### ISSUE THREAD

**Issue by szhorvat** [Galadirith/markdown-preview-plus#15]
Atom 0.174 gives me the following complaint upon startup with mardown-preview-plus 1.0.1:

![image](https://cloud.githubusercontent.com/assets/1212871/5793211/5b4ace0c-9f09-11e4-827a-a0d833815fe5.png)

**Comment by Galadirith** [comment]
@szhorvat I'm so sorry its taken me a week to get round to fixing this, thank you for flagging it :D All depreciated errors should now have vanished from `v1.1.0`

**Comment by szhorvat** [comment]
Thanks!  It never really caused a problem and it was really a quick fix, considering that most other packages I use still cause these deprecation warnings.
