### ISSUE TITLE
unable to preview Pandoc slides

### ISSUE THREAD

**Issue by jronallo** [Galadirith/markdown-preview-plus#151]
Pandoc can create slide decks. In trying to preview a dzslides slide show with the following options the whole editor view pane becomes completely black: 

--write=dzslides, --standalone

I'd love to have an option to preview slide decks in Atom using Pandoc.

**Comment by Galadirith** [comment]
@jronallo Thanks for opening the issue and I really apologise for taking so long to reply. Taking a look at an [example output](http://pandoc.org/demo/example16a.html) it seems that the `dzslides` output renders with embedded scripts which are needed for it to work. Scripts are striped out when the preview pane is render which I believe is the source of the problem.

Unfortunately this is something I would be able to fix. I will close this issue, but please feel free to post back with any other comments. Thanks again @jronallo
