### ISSUE TITLE
Scroll the preview pane with the editor pane

### ISSUE THREAD

**Issue by clbarnes** [Galadirith/markdown-preview-plus#152]
At least ensuring that the line currently being edited is visible. Once you've got more than a page of code it's a pain to keep panning the preview pane down with every new line typed.

**Comment by OJFord** [comment]
To expand on this, I think it's often useful to have it freely-positionable, allowing us to refer to somewhere else in the document while writing.

However it would be useful to have a "lock to cursor and centre" mode - especially when writing LaTeX.

**Comment by OJFord** [comment]
I've just seen #9 - @clbarnes this seems to be a duplicate.

**Comment by alexellis** [comment]
+1, not sure exactly what the outcome of #9 was... is this work in progress? @OJFord

**Comment by OJFord** [comment]
@alexellis It's in [the roadmap](https://github.com/Galadirith/markdown-preview-plus/issues/89) for release 2.4.0

**Comment by Galadirith** [comment]
@clbarnes @OJFord @alexellis Thanks so much everyone for your interest in the feature and I really apologise for taking so long to respond.

This has been a long requested feature which I would also love to see. But I don't any longer have the time I once had to dedicate to improving MPP and auto syncing the scroll of the editor and preview pane has been one of the casualties. 

While I am hopeful at some point I may be able to implement this, I am afraid I can't provide any expected release date.

I will close this issue in favour of #9. Please do post back to #9 if you have any thought or comments on this feature request. Thanks again everyone.
