### ISSUE TITLE
List Levels not showing

### ISSUE THREAD

**Issue by Agnishom** [Galadirith/markdown-preview-plus#153]
The list does not show proper leveling.

For example the following does not work:

1. A
2. B
3. C
 1. C1
 2. C2

**Comment by MAccadia** [comment]
Hi, it works for me with a 3 spaces indentation. It is coherent with [CommonMark Specs](http://spec.commonmark.org).

Here is what I've found  : 

>How much indentation is needed for a sublist? The spec says that continuation paragraphs need to be indented four spaces, but is not fully explicit about sublists. It is natural to think that they, too, must be indented four spaces, but Markdown.pl does not require that. This is hardly a “corner case,” and divergences between implementations on this issue often lead to surprises for users in real documents. (See this comment by John Gruber.)

So, CommonMark spec states : 

>The rules for sublists follow from the general rules above. A sublist must be indented the same number of spaces a paragraph would need to be in order to be included in the list item.

That means 3 spaces in your case.

**Comment by Galadirith** [comment]
@Agnishom Thanks for opening the issue and I really apologise for taking so long to reply. @MAccadia I really appreciate your input.

We use [`markdown-it`](https://github.com/markdown-it/markdown-it) as our markdown parser which follows the CommonMark spec. As @MAccadia said that means you need to use 3 space indentation for nested lists to work.

In theory its possible to relax the syntax with with a [plugin](https://www.npmjs.com/browse/keyword/markdown-it-plugin) but this wouldn't be something I would have time to implement.

I will close this issue, but please feel free to post back with any comments. Thanks again @Agnishom @MAccadia .
