### ISSUE TITLE
Minimum pandoc options needed to preview a markdown document? Not working.

### ISSUE THREAD

**Issue by breschke** [Galadirith/markdown-preview-plus#154]
I'm trying to use the pandoc parser (eventually, with bibliography parsing). I can't get the simplest .md document to preview when I select the pandoc parser option. I have specified the path to my pandoc executable. I currently don't have any options for the command line arguments. Whenever I enter the keybindings for markdown preview, it shows a blank document in the right panel. No such issue when the pandoc parser is disabled. What are the minimum options needed in order to preview a markdown document using the pandoc parser?

Separate note: It's not clear in the docs whether I can use the pandoc parser to preview a markdown document as a pdf. That, plus citation support, is my main interest in using the pandoc parser with MPP. I assumed the correct (comma separated) commandline arguments to enter would be as follows:

> --standalone, --output=test1.pdf

**Comment by Galadirith** [comment]
@breschke Thanks for opening the issue and I'm sorry its taken me so long to reply.

I'm not able to reproduce your problem. To just use vanilla pandoc you shouldn't need to add any options to `Pandoc Options: Commandline Arguments`. Do you receive any errors when you enable pandoc and try to preview a document?

> It's not clear in the docs whether I can use the pandoc parser to preview a markdown document as a pdf

Unfortunately this isn't possible. The only supported output within Atom is HTML output.

**Comment by breschke** [comment]
Thanks for the reply--sometime between now and when I opened the issue, I got it to work and neglected to close the issue.

**Comment by Galadirith** [comment]
@breschke Great, really glad you got it working and thanks for closing the issue.
