### ISSUE TITLE
Error: pandoc-citeproc not found

### ISSUE THREAD

**Issue by mangecoeur** [Galadirith/markdown-preview-plus#157]
I'm having trouble using the pandoc citations in the preview, i get `pandoc exited with code 85: pandoc: Filter pandoc-citeproc not found`

I have pandoc installed via Cabal and I definitely have citeproc installed - it all works fine on the command line. An ideas? My only guess is that pandoc is can't find citeproc on $PATH, since on OSX your regular $PATH isn't available inside apps...

EDIT: Note that I DO have the "path" of pandoc correctly defined in the settings... perhaps markdown preview isn't prepending this path to the filter options?

**Comment by philomonk** [comment]
I have the same problem. To test what you're hinting at I copied the pandoc-citeproc executable to my root directory. When I run MPP then, the error message changes to ```pandoc exited with code 83: pandoc: Error running filter pandoc-citeproc
pandoc-citeproc: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)```

**Comment by jiku** [comment]
Had the same issue just now. You can try to add something like

```
process.env.PATH = ["/usr/bin",
                    "/usr/local/bin",
                    ].join(":")
```

to your init script (assuming `pandoc` and `pandoc-citeproc` are installed into /usr/local/bin like with Homebrew).

Seems it's to do with Atom and OS X

- [Regression related to process.env.PATH · Issue #550 · atom/electron](https://github.com/atom/electron/issues/550)
- [lsegal/atom-rst-preview - CoffeeScript](https://github.com/lsegal/atom-rst-preview#workaround-on-osx-for-pandoc-could-not-be-spawned-error)

**Comment by philomonk** [comment]
It worked! Thank you so much @jiku!

**Comment by jiku** [comment]
No worries. :)

**Comment by Galadirith** [comment]
@mangecoeur @philomonk @jiku Thanks so much for opening this issue and I really apologise for taking so long to respond.

@jiku I really appreciate the time you took to research a solution to this issue. As it seems this has a working solution I will close this issue. But if this problem is still affecting anyone please feel free to post back to this thread. Thanks again.

**Comment by rguareschi** [comment]
Works!!! Thanks @jiku
