### ISSUE TITLE
Font selection for Pandoc-Markdown preview

### ISSUE THREAD

**Issue by kleinbottle** [Galadirith/markdown-preview-plus#158]
I have just started using the atom editor and the MPP package. It works very well. Thanks for it.

How might I change the font in which the (HTML) preview is rendered? As a newcomer to Atom, I am somewhat overwhelmed by its customizability and also because I do not know where to change what to get a specific desired result. My apologies if this is off-topic here.

Thanks.

**Comment by Galadirith** [comment]
@kleinbottle Thanks for use MPP and I really apologise for taking so long to reply to you.

There are lots of great ways you can customise atom's fonts, but as you said it can be a little overwhelming. For changing things like fonts, I would suggest first looking at [basic-customization](http://flight-manual.atom.io/using-atom/sections/basic-customization/#_style_tweaks) in Atom's flight manual.

In this particular case for changing the font in the preview, first open up your custom stylesheet and you can do this by selecting **Atom > Stylesheet ...**. This in the file that it opens up, at the bottom you can add the following snippet of code
```css
div.update-preview {
  font-family: "Helvetica Neue", Helvetica, "Segoe UI", Arial, freesans, sans-serif;
}
```
In this particular case it will set the font in the preview pane to Helvetica Neue. If that isn't avilable it will try to use Helvetica. If that isn't available it will try to use Segoe UI and so on. This is how you can change the font.

I really hope that helps. I will close this issue but please feel free to post back with any further comments. Thanks again @kleinbottle.
