### ISSUE TITLE
Atom hangs and crashes when trying to preview

### ISSUE THREAD

**Issue by jcpsantiago** [Galadirith/markdown-preview-plus#159]
Just installed Atom and MPP. The default config works, but I want to see my citations and my YAML block properly rendered, so I tweaked the config:

```
  "markdown-preview-plus":
    pandocBibliography: true
    pandocRemoveReferences: false
    pandocBIBFile: "/home/mariachi/Dropbox/Working/library.bib"
    pandocCSLFile: "/home/mariachi/.pandoc/csl/apa.csl"
    enablePandoc: true
    pandocPath: "/usr/bin/pandoc"
    pandocArguments: [
      "pandoc -S --template=/home/mariachi/.pandoc/templates/html.template --css=/home/mariachi/.pandoc/styles/marked/kultiad-serif.css --filter pandoc-citeproc --csl=/home/mariachi/.pandoc/csl/apa.csl"
    ]
    pandocMarkdownFlavor: "markdown+simple_tables+table_captions+yaml_metadata_block"
```
Is there a log or error message somewhere? I'm using Linux.

**Comment by Galadirith** [comment]
@jcpsantiago Thanks so much for using MPP and I'm really sorry its taken me so long to reply to you.

It looks like the problem you have is the `--template` option and subsequent `--css` option. The `--template` option implies the `--standalone` option which unfortunately isn't support when using the pandoc parser.

I will close this issue now, but please feel free to post back with any other comments. Thanks again @jcpsantiago.
