### ISSUE TITLE
Cannot install, seems .NET issue

### ISSUE THREAD

**Issue by zhidayat** [Galadirith/markdown-preview-plus#16]
I cannot install MPP and get the following error message below. I guess it is about wrong .NET framework problem.

> runas@1.2.0 install C:\Users\zulkifli\AppData\Local\Temp\apm-install-dir-11502
8-4700-gy5iwj\node_modules\markdown-preview-plus\node_modules\pathwatcher\node_m
odules\runas
> node-gyp rebuild

C:\Users\zulkifli\AppData\Local\Temp\apm-install-dir-115028-4700-gy5iwj\node_mod
ules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas>node "c:\
Users\zulkifli\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\npm
\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.Targets(983,5): w
arning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4
.0" were not found. To resolve this, install the SDK or Targeting Pack for this
framework version or retarget your application to a version of the framework for
 which you have the SDK or Targeting Pack installed. Note that assemblies will b
e resolved from the Global Assembly Cache (GAC) and will be used in place of ref
erence assemblies. Therefore your assembly may not be correctly targeted for the
 framework you intend. [C:\Users\zulkifli\AppData\Local\Temp\apm-install-dir-115
028-4700-gy5iwj\node_modules\markdown-preview-plus\node_modules\pathwatcher\node
_modules\runas\build\runas.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297
,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.
TargetFrameworkVersion or PlatformToolset may be set to an invalid version numbe
r. [C:\Users\zulkifli\AppData\Local\Temp\apm-install-dir-115028-4700-gy5iwj\node
_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas\build
\runas.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
Win32.Targets(147,5): error : Required file "" is missing. [C:\Users\zulkifli\Ap
pData\Local\Temp\apm-install-dir-115028-4700-gy5iwj\node_modules\markdown-previe
w-plus\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]

> oniguruma@3.1.0 install C:\Users\zulkifli\AppData\Local\Temp\apm-install-dir-1
15028-4700-gy5iwj\node_modules\markdown-preview-plus\node_modules\highlights\nod
e_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild

C:\Users\zulkifli\AppData\Local\Temp\apm-install-dir-115028-4700-gy5iwj\node_mod
ules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_
modules\oniguruma>node "c:\Users\zulkifli\AppData\Local\atom\app-0.176.0\resourc
es\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\no
de-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.Targets(983,5): w
arning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4
.0" were not found. To resolve this, install the SDK or Targeting Pack for this
framework version or retarget your application to a version of the framework for
 which you have the SDK or Targeting Pack installed. Note that assemblies will b
e resolved from the Global Assembly Cache (GAC) and will be used in place of ref
erence assemblies. Therefore your assembly may not be correctly targeted for the
 framework you intend. [C:\Users\zulkifli\AppData\Local\Temp\apm-install-dir-115
028-4700-gy5iwj\node_modules\markdown-preview-plus\node_modules\highlights\node_
modules\first-mate\node_modules\oniguruma\build\oniguruma.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297
,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.
TargetFrameworkVersion or PlatformToolset may be set to an invalid version numbe
r. [C:\Users\zulkifli\AppData\Local\Temp\apm-install-dir-115028-4700-gy5iwj\node
_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\n
ode_modules\oniguruma\build\oniguruma.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
Win32.Targets(147,5): error : Required file "" is missing. [C:\Users\zulkifli\Ap
pData\Local\Temp\apm-install-dir-115028-4700-gy5iwj\node_modules\markdown-previe
w-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\bu
ild\oniguruma.vcxproj]

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Users\\zulkifli\\AppData\\Local\\atom\\app-0.176.0\\resources
\\app\\apm\\bin\\\\node.exe" "c:\\Users\\zulkifli\\AppData\\Local\\atom\\app-0.1
76.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig"
"c:\\Users\\zulkifli\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\.a
pmrc" "--userconfig" "C:\\Users\\zulkifli\\.atom\\.apmrc" "install" "C:\\Users\\
zulkifli\\AppData\\Local\\Temp\\d-115028-4700-1gec9ec\\package.tgz" "--target=0.
20.0" "--arch=ia32" "--msvs_version=2010"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! runas@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@1.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by Galadirith** [comment]
@zhidayat I'm really sorry about your problems installing. 

The problem I belive is with [node-gyp](https://github.com/TooTallNate/node-gyp) and the subtle dependencies it has on different versions of Visual Studio. So I would definitely recommend looking at [Installation](https://github.com/TooTallNate/node-gyp#installation) instructions for `node-gyp`, and it might tell you what your missing (Note that it suggests installing Microsoft Visual Studio C++ 2010 Express, but the link points somewhere odd, at least for me. Instead you can go directly to download the express version [here](http://www.visualstudio.com/en-us/downloads/download-visual-studio-vs#DownloadFamilies_4)). Plus having a look at some of the issues there such as TooTallNate/node-gyp#168. It would probably be faster for you to have a look through those.

That said I'll do everything I can to try and get MPP up and working for you :D So can I ask which version of windows are you using, and have you ever installed any version of visual studios on your computer, or any Microsoft C++ re-distributable package? For reference I'm running Windows 7 service pack 1 and I have Microsoft Visual Studio C++ 2010 installed.

Please let me know if you have more questions and I'll get back to you as soon as I can :D

**Comment by zhidayat** [comment]
@Galadirith Thank you for your response. 
I am sorry for my incomplete information.
I am using Win 7 64bit with SP 1. 
I have: 
MS C++ 2010 x86 and x64 redistributable
MS C++ Compilers 2010 standard
MS .NET framework 4.5.1
Python 2.7.9

Thanks for the link that pointing to the node-gyp problem. I have to admit that I do not fully understand to the discussion.

**Comment by Galadirith** [comment]
@zhidayat No problem at all, and you definitely didn't give me incomplete information its just my job to ask plenty of questions :D 

So looking at the components you already have installed, it does look like the missing component is [Visual C++ 2010 Express](http://www.visualstudio.com/en-us/downloads/download-visual-studio-vs#DownloadFamilies_4), it installs extra files not found in any of the components you have installed. 

If you follow that link you'll find a page where you can download it. It seems that you need to sign in with a Microsoft ID (for example an @hotmail.com email address or something similar). I haven't found a way to download it without one, but please let me know if that's a problem.

Let me know how that goes and we can take it from there :D

**Comment by Galadirith** [comment]
If you can't or don't want to sign in with a Microsoft ID, I have found that you can actually download an `.iso` file if you click on the [Visual Studio 2010 Express All-in-One ISO](http://www.visualstudio.com/en-us/downloads/download-visual-studio-vs#DownloadFamilies_4) option which will allow you to install Visual C++ 2010 Express. To use that you would either have to burn the file to a disc or use a virtual disk program. Its a more complicated alternative, but it is an alternative :D  

Let me know if you would prefer this route and if you need any help following it :D

**Comment by zhidayat** [comment]
@Galadirith the package has been installed smoothly, after installing MS VC++ 2010 Express. Thank you for developing the great package.
The installation perhaps the most difficult.

**Comment by Galadirith** [comment]
@zhidayat Thats fantastic great news, I hope you enjoy using it :D
