### ISSUE TITLE
Tables do not respect theme color

### ISSUE THREAD

**Issue by jojje** [Galadirith/markdown-preview-plus#161]
Markdown preview of tables using the default Atom theme (light text on dark background) renders the heading as white text on white background, making it invisible.

Further, the background for the table itself is glaring white, when it would be expected to have the same color as the other rendered markdown content in the preview.

[Screenshot](http://s9.postimg.org/d735zov3j/atom_markdownpp_table_rendering_bug.png)

Environment where the bug was observed:
* Atom version: 1.2.4 (fresh install, no plugins but MPP)
* Plugins installed: MPP 2.2.2 (via embedded Atom plugin installer)
* Theme: Default Atom theme (One Dark for UI + Syntax)
* OS: Windows 7 (64bit)

**Comment by timlyo** [comment]
I'm still getting this issue.

Atom: 1.4.0-1
Theme: One Dark
OS: Antergos Linux

**Comment by Galadirith** [comment]
@jojje @timlyo Thanks so much for reporting this issue and I really apologise for taking so long to respond to it.

I have just merged in #192 which should correct this issue and will be publishing this shortly. I will close this issue now but if you still experience the problem please feel free to comment back her. Thanks again.

**Comment by timlyo** [comment]
> I really apologise for taking so long to respond to it.

Never forget that you are the one giving up your time. We aren't entitled to anything from you, you do this voluntarily.

Thanks for the great work :)

**Comment by Galadirith** [comment]
@timlyo I'm always so honored and humbled when people choose to use my code and so my time is something I love giving.

But I really appreciate your words @timlyo. You've got a really kl range of things your working on :D
