### ISSUE TITLE
Cannot control picture size in markdown-preview-plus

### ISSUE THREAD

**Issue by JacobIsrael123** [Galadirith/markdown-preview-plus#164]
In markdown-preview ```<img src="pic1.png" alt="", style="width: 700px"/>``` could control picture size, but when I change to markdown-preview-plus. It could not be use for size control. 

Is it possible to add feature like ![][picture.png =12x12] to control picture like other markdown editor do?

Or it the markdown-preview-plus has a way to control picture size, please tell me how to do it. 

Thank you very much.

**Comment by Galadirith** [comment]
@JacobIsrael123 Thanks so much for using MPP and I really apologise for taking so long to reply to you.

MPP does support this syntax however I think you have a mistake in your code, it should be
```html
<img src="pic1.png" alt="" style="width: 700px"/>
```
ie removing the `,` after the `alt=""`. This should now work for you.

I will close this issue, but please let me know if you have any further problems related to this issue. Thanks again @JacobIsrael123.
