### ISSUE TITLE
Image cached and never updated

### ISSUE THREAD

**Issue by MatteoRagni** [Galadirith/markdown-preview-plus#167]
This package is perfect for my local notes with equations and I love it, but due to compatibility with :octocat: README, I've started to insert equations as image locally generated images with `latex + dvigif`.

I use markdown plus to get a preview on my README, but image equations are not updated when regenerated/modified if image name does not change. Maybe is a problem of caching. How can I disable cache in Markdown preview for images?

Image are 
 * not updated even if I close and than re-open preview tab
 * updated if I close completely atom

Thank you

**Comment by Galadirith** [comment]
@MatteoRagni Thanks so much for using MPP and I really apologise for taking so long to reply.

Image caching is actually a problem that is managed by atom not by MPP. However we did introduce a way to always use the most up to date image in #63. I have tested this locally and it does still work for me.

We use [`pathWatcher`](https://github.com/atom/node-pathwatcher) to detect when an image has changed, and it might be that there is some incompatibility between how your images are being updated and how `pathWatcher` detects changes in files.

Unfortunately I don't know how else to be of help here. If there are any more details about your setup that you can provide I may be able to try it locally.

Please let me know what you think, and as always please post back with any comments. Thanks again @MatteoRagni.

**Comment by MatteoRagni** [comment]
Thank you! I'm not sure why, but after an update of atom I think the problem was solved. But I forgot to close this issue :sweat_smile:.

**Comment by Galadirith** [comment]
No problem @MatteoRagni thanks for letting me know. Glad everything is now working :D
