### ISSUE TITLE
text.md not one of the default scopes

### ISSUE THREAD

**Issue by duppypro** [Galadirith/markdown-preview-plus#168]
The preview pane did not open for me until I changed the Settings -> Grammars to 'text.md'.

Expected: text.md would be one of the default scopes

**Comment by polarathene** [comment]
Was just wondering why I was unable to toggle the preview. Thanks for the solution :) This really should be included as a default.

**Comment by Galadirith** [comment]
@duppypro @polarathene thanks for the discussion on this issue and I really apologise for taking so long to reply. 

I have added `text.md` as a default grammar which will hopefully prevent this issue for others in the future. Please feel free to post back if you still have any problems related to this issue. Thanks again.
