### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by kurtharriger** [Galadirith/markdown-preview-plus#169]
Is it possible to change font size?  
Cmd +/- does not appear to work.

**Comment by Galadirith** [comment]
@kurtharriger Thanks for using MPP and I really apologise for taking so long to reply.

You can change the font size although it is a little more involved than `cmd++` or `cmd+-`. First open up your custom stylesheet and you can do this by selecting **Atom > Stylesheet ...**. Then in the file that it opens up, at the bottom you can add the following snippet of code
```css
div.update-preview {
  font-size: 14px;
}
```
Set the `font-size` to what ever you prefer. I hope that helps.

I will close this issue not, but if you have any other comments please feel free to post back. Thanks again @kurtharriger.
