### ISSUE TITLE
$N\times N$ won't render properly

### ISSUE THREAD

**Issue by szhorvat** [Galadirith/markdown-preview-plus#17]
There are certain LaTeX snippets that don't render properly.  

Example document to reproduce the problem:

```
An $N\times N$ grid.
```

![image](https://cloud.githubusercontent.com/assets/1212871/5965960/582bd810-a7ce-11e4-8e9f-435d1dccf02c.png)

Atom 0.176, markdown-preview-plus 1.1.0, mathjax-wrapper 0.1.0

Can anyone else reproduce this problem?

I'm think it wasn't present earlier, but I don't know when it broke.

**Comment by szhorvat** [comment]
Comparing with StackExchange's MathJax-based rendering for verification:

![image](https://cloud.githubusercontent.com/assets/1212871/5966035/d4795776-a7ce-11e4-813e-792aa57ba6b2.png)

**Comment by Galadirith** [comment]
@szhorvat Thanks for the report. I've identified the problem in my fork of [marked](https://github.com/Galadirith/marked/blob/991b9beab5453ab4366f3f2881a365f0cfd816a0/lib/marked.js#L547) which strips any white space characters that appear before the character placed before the closing `$` delimiter (that sounds like a bad joke!) 

Its a couple of lines to fix, but I need to make sure I have suitable unit test's in place (Galadirith/markdown-preview-plus#18) before I push out a fix.

Thanks again @szhorvat
