### ISSUE TITLE
Links within lists don't render correctly

### ISSUE THREAD

**Issue by iDev0urer** [Galadirith/markdown-preview-plus#170]
When doing a list like this:

```markdown
* (Hello)[#]
* (World)[#]
```

The links don't get parsed as links

**Comment by iDev0urer** [comment]
I'm an idiot and got the parentheses and brackets mixed up :tired_face:

**Comment by Galadirith** [comment]
@iDev0urer Glad you were able to resolve this yourself and thanks for closing the issue :D
