### ISSUE TITLE
Pandoc not rendering meta title/author

### ISSUE THREAD

**Issue by EntilZha** [Galadirith/markdown-preview-plus#173]
I am testing a file like this
```
---
title: Homework 1
author: Pedro Rodriguez
---

testing
```

Which displays only `testing` on the page produced for preview. I have these options enabled `-V geometry:margin=1in --standalone` and when running `pandoc` from the command line like `pandoc -V geometry:margin=1in --standalone test.md` get this:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <meta name="author" content="Pedro Rodriguez" />
  <title>Homework 1</title>
  <style type="text/css">code{white-space: pre;}</style>
</head>
<body>
<div id="header">
<h1 class="title">Homework 1</h1>
<h2 class="author">Pedro Rodriguez</h2>
</div>
<p>testing</p>
</body>
</html>
```

which is producing the correct header. Any ideas why its doing this?

**Comment by Galadirith** [comment]
@EntilZha Thanks for opening the issue and I really apologise for taking so long to reply.

It looks like the problem here is the `--standalone` option. Unfortunately MPP doesn't support this option as it doesn't just generate the body of a html page but also all the `<head>` content to. There is no practical way around this, as MPP is effectively placing HTML snippets (ie without `<head>` content etc) into a page that already has `<head>` etc.

I'm sorry I can't give you better new on this issue. I will close this issue now, but please feel free to reply if you have any further comments related to this issue.

**Comment by wuffi** [comment]
I have the same issue but even without using the `--standalone`` option.
Do I need to toggle any options to enable parsing for the meta title/author?

`pandoc -f markdown my_file.md -o my_file.pdf` renders everything correctly

**Comment by lierdakil** [comment]
```html
<div id="header">
<h1 class="title">Homework 1</h1>
<h2 class="author">Pedro Rodriguez</h2>
</div>
```
is defined in Pandoc's template, which is used only with `--standalone`. You can make your own template which would only include html body, and not head or outer html, and use that with `--standalone --template=my_template_file.html`

Here is something to start you with (based on default html template, obtained via `pandoc -D html`):

```html
$for(include-before)$
$include-before$
$endfor$
$if(title)$
<div id="$idprefix$header">
<h1 class="title">$title$</h1>
$if(subtitle)$
<h1 class="subtitle">$subtitle$</h1>
$endif$
$for(author)$
<h2 class="author">$author$</h2>
$endfor$
$if(date)$
<h3 class="date">$date$</h3>
$endif$
</div>
$endif$
$if(toc)$
<div id="$idprefix$TOC">
$toc$
</div>
$endif$
$body$
$for(include-after)$
$include-after$
$endfor$
```

**Comment by wuffi** [comment]
Thanks a lot for your answer.
Using the `--standalone` option makes `pandoc` perfectly render everything.

Somehow, I misunderstood the previous post: I thought I would need to omit the `--standalone` option in order to have `pandoc` render my title.
