### ISSUE TITLE
Autoscroll

### ISSUE THREAD

**Issue by NobbZ** [Galadirith/markdown-preview-plus#177]
Please make the Preview-Window autoscroll such that the edited area is visible.

Especially when writing larger stuff, it is really annoying, that I need to scroll manually every couple of lines, when editing the end of the document.

**Comment by OJFord** [comment]
See issues #9, #137, #152.

As I've commented on one of the above, it's in the 2.4.0 release roadmap.

**Comment by Galadirith** [comment]
@NobbZ @OJFord Thanks for you interest in this feature request.

@OJFord thanks once again for aggregating the issue on this feature request. To summarise https://github.com/Galadirith/markdown-preview-plus/issues/152#issuecomment-201942633 unfortunately I don't have the time any longer to attempted implementing this feature request.

> it's in the 2.4.0 release roadmap

I'm sorry to say I have removed it from the 2.4.0 roadmap for the foreseeable future. I really apologise again not being able to implement this.

I am closing this issue in favour of #9. Please do post back to #9 if you have any thought or comments on this feature request. Thanks again.
