### ISSUE TITLE
Images are not shown when path contains a space

### ISSUE THREAD

**Issue by chrahunt** [Galadirith/markdown-preview-plus#187]
Example markdown:

```md
# Test

![](test 2\af939f942da4a29216e32d2e1f55e3ce.png)
```

Output in markdown panel:

![image](https://cloud.githubusercontent.com/assets/2312275/13549476/d16e12f6-e2d3-11e5-8c76-83b8a6980019.png)

Output in markdown-preview markdown panel:

![image](https://cloud.githubusercontent.com/assets/2312275/13549484/eb5ad4f6-e2d3-11e5-92f5-940613c24540.png)

**Comment by Kkevsterrr** [comment]
Was about to submit this issue - thanks for submitting and I look forward to a fix.

**Comment by chrahunt** [comment]
This is actually mentioned in markdown-it/markdown-it#72 and the solution there is sufficient:

> [Surround url with < > or escape spaces with &#92;](https://markdown-it.github.io/#md64=eyJzb3VyY2UiOiJJbnZhbGlkOlxuXG4hW0FsdCB0ZXh0XShodHRwOi8veXVtbC5tZS9kaWFncmFtL3NjcnVmZnkvY2xhc3MvW0FkbWluaXN0cmF0b3JdLV5bUGVyc29uXSwgW1BlcnNvbl0tXltQYXJ0eV0pXG5cblF1b3RlZCB3aXRoIGA8ID5gOlxuXG4hW0FsdCB0ZXh0XSg8aHR0cDovL3l1bWwubWUvZGlhZ3JhbS9zY3J1ZmZ5L2NsYXNzL1tBZG1pbmlzdHJhdG9yXS1eW1BlcnNvbl0sIFtQZXJzb25dLV5bUGFydHldPilcblxuRXNjYXBlZCBzcGFjZTpcblxuIVtBbHQgdGV4dF0oaHR0cDovL3l1bWwubWUvZGlhZ3JhbS9zY3J1ZmZ5L2NsYXNzL1tBZG1pbmlzdHJhdG9yXS1eW1BlcnNvbl0sXFwgW1BlcnNvbl0tXltQYXJ0eV0pIiwiZGVmYXVsdHMiOnsiaHRtbCI6ZmFsc2UsInhodG1sT3V0IjpmYWxzZSwiYnJlYWtzIjpmYWxzZSwibGFuZ1ByZWZpeCI6Imxhbmd1YWdlLSIsImxpbmtpZnkiOnRydWUsInR5cG9ncmFwaGVyIjp0cnVlLCJfaGlnaGxpZ2h0Ijp0cnVlLCJfc3RyaWN0IjpmYWxzZSwiX3ZpZXciOiJodG1sIn19), if you need spaces and other strange chars there. That's described in the [commonmark spec](http://spec.commonmark.org/0.18/#link-destination).

No reason to diverge from the spec when there's a nice solution already (< >).

**Comment by Galadirith** [comment]
@chrahunt Thanks so much for opening this issue and I really apologise for not being able to reply until now. I'm glad and grateful that you were able to track down a solution in markdown-it/markdown-it.

Thanks again.

**Comment by lukejanicke** [comment]
The **markdown-it** solution does not appear to work any more. See the screenshot below.

The [CommonMark Spec](https://spec.commonmark.org/0.28/) does not specify anything about file names for [images](https://spec.commonmark.org/0.28/#images). However, for links it says “The destination cannot contain spaces or line breaks, even if enclosed in pointy brackets” (see examples [463](
https://spec.commonmark.org/0.28/#example-463), [464](
https://spec.commonmark.org/0.28/#example-464), [465](
https://spec.commonmark.org/0.28/#example-465), [466](
https://spec.commonmark.org/0.28/#example-466)). Although, later it allows: “Parentheses and other symbols can also be escaped, as usual in Markdown” (see example [471](
https://spec.commonmark.org/0.28/#example-471)). And, of course, later for HTML it allows “this spec does not enforce any particular policy for rendering URLs in HTML or other formats”.

I interpret this too mean that the CommonMark Spec intentionally does not permit images with spaces in file names, even though most HTML renderers do. It does not appear to be an oversight, but the case for images is indirectly specified via the Links section of the spec.

This is quite an inconvenience but one that it seems we must accept.

<img width="1440" alt="screen shot 2019-01-02 at 11 37 54pm" src="https://user-images.githubusercontent.com/837028/50599057-ce20c880-0ee7-11e9-89fa-566e0980281c.png">
