### ISSUE TITLE
Square roots in fractions in display math don't render the overline

### ISSUE THREAD

**Issue by szhorvat** [Galadirith/markdown-preview-plus#19]
When there's a square root in the numerator of a fraction in display math mode, the upper part of the square root sign doesn't render.

Test case:

```
\[ \frac{-b \pm \sqrt{b^2-4ac}}{2a} \]
```

![image](https://cloud.githubusercontent.com/assets/1212871/6024302/2f0feb9c-ab98-11e4-89fe-d21085d95bc8.png)

Notice that the top part of the square root sign is missing.

**Comment by leipert** [comment]
Maybe a bug with the line-height?

**Comment by leipert** [comment]
The line actually renders to:
```
<span style="position: absolute; clip: rect(2.99em 1000em 3.397em -0.536em); top: -4.238em; left: 0.952em;">...</span>
```
If i manually correct the top value to `-4.138em` everything looks fine:

![screen shot 2015-03-09 at 01 40 30](https://cloud.githubusercontent.com/assets/2906107/6548553/52485b88-c5fd-11e4-9e50-398e44dc547e.png)

I suspect it is an error from MathJax

**Comment by leipert** [comment]
This issue does not seem to happen anymore. Tested with

```
atom: 1.0.2
markdown-preview-plus: 1.6.0
mathjax-wrapper: 0.1.0
```
