### ISSUE TITLE
Preview panel does not stick to the end of the file

### ISSUE THREAD

**Issue by Arcesilas** [Galadirith/markdown-preview-plus#197]
Hi,

Thanks for your work with this package!

I'm not sure whether the bug I'm reporting is related to MPP or to Atom itself.

When editing a .md file, i scroll down the preview to see what I'm typing. When I save the file, the preview scrolls up by several lines. I'm not using any sync package to keep the preview aligned with the editor, I don't really mind to scroll manually. But I think the preview should not scroll without any action from myself.

When at another position, the preview panel does not scroll up when saving...

**Comment by Arcesilas** [comment]
Sorry... Seems I had a conflict with markdown-preview core package, which I disabled, but without closing/opening the preview panel...

**Comment by Galadirith** [comment]
@Arcesilas no problem at all. Glad you were able to fix it yourself. Please let me know if you have any other problems :D
