### ISSUE TITLE
$$ in inline code interferes with display math separator

### ISSUE THREAD

**Issue by szhorvat** [Galadirith/markdown-preview-plus#20]
`$$` isn't handled properly in inline code and it interferes with actual display math separators.

This is fine:

![image](https://cloud.githubusercontent.com/assets/1212871/6024340/71393c76-ab98-11e4-844a-519a53abfda9.png)

This is also fine:

![image](https://cloud.githubusercontent.com/assets/1212871/6024375/b1923b10-ab98-11e4-9e27-670820bf47c6.png)

This is broken:

![image](https://cloud.githubusercontent.com/assets/1212871/6024338/66d80e42-ab98-11e4-98cd-71092430d6b8.png)

Test case:

```
This is broken `$$`

$$
a+b
$$
```

**Comment by Galadirith** [comment]
@szhorvat Thanks for the report. I've identified the problem in my fork of [marked](https://github.com/Galadirith/marked/blob/mathjax/lib/marked.js#L78) which parses the source document for `$$` delimiters before inline code delimiters are parsed.

This was probably introduced way back when I fixed Galadirith/markdown-preview-plus#2 to allow `$$` delimiters to start anywhere, not just on newlines. What I need to do is add some more carefully considered conditions under which `$$` should not be considered an opening delimiter to a displayed maths block. I'll update the issue when I've pushed a fix.

Thanks again @szhorvat, its really appreciated.
