### ISSUE TITLE
offline mathjax engine is possible or not

### ISSUE THREAD

**Issue by Lmaths** [Galadirith/markdown-preview-plus#208]
Sometimes we should use a offline mathjax engine, this is possible for this plugin?

**Comment by chrahunt** [comment]
Dependencies are resolved and downloaded when the plugin is installed. MathJax is downloaded and saved alongside `markdown-preview-plus` in your `.atom/packages` folder and that is what is used by the plugin to render the math in your document. Is that enough or was there something else you were getting at?

**Comment by Lmaths** [comment]
When open the Atom again, the preview about the math disappeared. I toggled the `markdown-preview-plus`  again, then it works.  
 Thank you very much.

**Comment by chrahunt** [comment]
Any time! Make sure to close the issue.
