### ISSUE TITLE
Jekyll's {% highlight %} tag is not recognized

### ISSUE THREAD

**Issue by saikek** [Galadirith/markdown-preview-plus#212]
Jekyll's Markdown tag
{% highlight xml %}

{% endhighlight %}
is not recognized properly - in preview pane it either skips completely the highlighted section or shows only part of text to be higlighted.

**Comment by chrahunt** [comment]
Yup, that's correct, you should be using \`\`\` around blocks you want highlighted. Markdown preview plus uses [markdown-it](https://github.com/markdown-it/markdown-it) which adheres to CommonMark. See their syntax reference [here](http://commonmark.org/help/), it's mostly the same on the surface as other implementations but that has links to more detailed descriptions if you need it.

**Comment by saikek** [comment]
Perfect, than let's close it.
