### ISSUE TITLE
Installation failed via apm on OS Yosemite, and both via apm and GUI on OS Lion

### ISSUE THREAD

**Issue by projetmbc** [Galadirith/markdown-preview-plus#23]
Hello, 
I can't install your so wonderful package. Here is the messages sent to me.

----
npm WARN locking Error: EACCES, open '/Users/projetmbc/.atom/.node-gyp/.atom/.apm/_locks/markdown-preview-plus-b495b7e5ea2bf5b2.lock'
npm WARN locking  /Users/projetmbc/.atom/.node-gyp/.atom/.apm/_locks/markdown-preview-plus-b495b7e5ea2bf5b2.lock failed { [Error: EACCES, open '/Users/projetmbc/.atom/.node-gyp/.atom/.apm/_locks/markdown-preview-plus-b495b7e5ea2bf5b2.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/projetmbc/.atom/.node-gyp/.atom/.apm/_locks/markdown-preview-plus-b495b7e5ea2bf5b2.lock' }
npm ERR! Darwin 12.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/.apmrc" "--userconfig" "/Users/projetmbc/.atom/.apmrc" "install" "/private/var/folders/7l/497f8g2x0jd_qr7jljl2gdx00000gn/T/d-11519-505-aincvm/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0

npm ERR! Attempt to unlock /private/var/folders/7l/497f8g2x0jd_qr7jljl2gdx00000gn/T/apm-install-dir-11519-505-1jg9y5u/node_modules/markdown-preview-plus, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/7l/497f8g2x0jd_qr7jljl2gdx00000gn/T/apm-install-dir-11519-505-1jg9y5u/npm-debug.log

**Comment by Galadirith** [comment]
@projetmbc I really sorry I haven't been able to reply to you sooner, hopefully we can get it installing and working quickly :D.

It does look like the problem is with user permissions so would suggest first that you try running `apm` with admin privileges if you haven't already: 
````bash
sudo apm install markdown-preview-plus
````

Also make sure that you have the latest version of [git installed](http://git-scm.com/download/mac) as older versions of git have been a source of similar issues on windows (however I am not sure to what extend if at all that affects OS X).

Could I ask if you have had problems installing any other packages to Atom? Also which version of Atom are you currently using?

Please let me know how everything goes and we can take it from there :D

**Comment by projetmbc** [comment]
I have git on my Mac (OS: Moutain Lion). Here is a terminal session.

    macbook-pro:~ projetmbc$ git --version
    git version 2.2.1

What is strange is that installing via Atom, and not amp, I've got this message:

    Failed to install markdown-preview-plus because Git was not found.
    The markdown-preview-plus package has module dependencies that cannot
    be installed without Git.
    You need to install Git and add it to your path environment variable
    in order to install this package.
    Run apm -v after installing Git to see what version has been detected.

Here is now the output of amp -v:

    apm  0.134.0
    npm  2.3.0
    node 0.10.35
    python 3.4.2
    git 2.2.1

How can I fixed that ?

**Comment by Galadirith** [comment]
@projetmbc thanks for the info really helpful.

So the git problem would suggest your `PATH` environment variable isn't configured properly for git. Here is my suggestion on how to fix that (information is taken from [here](http://stackoverflow.com/questions/1835837/git-command-not-found-on-os-x-10-5)):

1. Open up the file `~/.profile` in a text editor. One way you should be able to do this from a terminal is:

  ````bash
  open -a TextEdit ~/.profile
  ````

  (There are probably mush better ways, but I don't spend a lot of time on OS X, please ping me back if your having problems opening `~/.profile`)
2. Add the following line to the end of the file:
    ````bash
    export PATH=$PATH:/usr/local/git/bin
    ````
3. Your computer may now require a restart to load the correct `PATH` variable.

This should fix the git error in Atom's GUI, please let me know how it goes. This may or may not fix the previous problem you had, but we'll see what happens after this. 

I did also notice that the current version of python you have installed is a `3.X.X` version. [`npm-gyp`](https://github.com/TooTallNate/node-gyp#installation) (`npm-gyp` is installed with `node`) is used to install the package, which only supports [Python `2.7.X`](https://www.python.org/downloads/release/python-279/). There is no reason you should no this, and its something I really must add to the installation instructions.

Now using `3.4.2` may well be fine, and so far it doesn't look like the version of Python has been the cause any of the errors, but its something we might think about if other solutions don't work.

Thanks @projetmbc :D

**Comment by projetmbc** [comment]
Here is my path

    :/usr/local/git/bin:/Users/projetmbc/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/texbin

I have tried a second time. Here are the errors sent.

    > runas@2.0.0 install /private/tmp/apm-install-dir-115111-318-irx0kc/node_modules/markdown-preview-plus/node_modules/pathwatcher/node_modules/runas
    > node-gyp rebuild


    > oniguruma@4.0.0 install /private/tmp/apm-install-dir-115111-318-irx0kc/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
    > node-gyp rebuild


    npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) 
    npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) 
    shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
    shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

    node.js:838
        var cwd = process.cwd();
                          ^
    Error: EACCES, permission denied
        at Function.startup.resolveArgv0 (node.js:838:23)
        at startup (node.js:58:13)
        at node.js:929:3
    shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
    shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

    node.js:838
        var cwd = process.cwd();
                          ^
    Error: EACCES, permission denied
        at Function.startup.resolveArgv0 (node.js:838:23)
        at startup (node.js:58:13)
        at node.js:929:3
    npm ERR! Darwin 12.6.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/.apmrc" "--userconfig" "/Users/projetmbc/.atom/.apmrc" "install" "/private/tmp/d-115111-318-164wmhs/package.tgz" "--target=0.21.0" "--arch=x64"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.3.0
    npm ERR! code ELIFECYCLE

    npm ERR! runas@2.0.0 install: `node-gyp rebuild`
    npm ERR! Exit status 8
    npm ERR! 
    npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the runas package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls runas
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /private/tmp/apm-install-dir-115111-318-irx0kc/npm-debug.log

**Comment by Galadirith** [comment]
@projetmbc Thanks for the report back. If you are happy to do so what I would like to try is a full manual install through node rather than through Atom; I want to cut out as many places as we can where you might loose permission to read and write stuff. 

So here are the steps you can take, make sure to run any commands from the terminal using `sudo`:

1. Download markdown-preview-plus from [here](https://github.com/Galadirith/markdown-preview-plus/archive/v1.2.0.tar.gz) and inside that archive file you'll find a folder called `markdown-preview-plus-1.2.0`. Unpack its contents into `~/.atom/packages/markdown-preview-plus` such that you now have folders like:
  
  ````bash
  ~/.atom/packages/markdown-preview-plus/assets
  ~/.atom/packages/markdown-preview-plus/imgs
  ...
  ````
  
  (alternatively if you are comfortable doing it you could `git clone` [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) into `~/.atom/packages`).
2. Now open a terminal and move to the directory `~/.atom/packages/markdown-preview-plus`
3. Run `npm install`
4. Assuming there are no errors run `apm rebuild`
5. If all went well markdown-preview-plus should now be available in Atom.

Let me know if you have a problem following any of the steps and let me know the result as soon as you are able to. Thank @projetmbc :D

**Comment by projetmbc** [comment]
Ok, no nmp is found… Does atom come with the npm or do I must install nodes?

**Comment by Galadirith** [comment]
@projetmbc I'm sorry I shouldn't have assumed you necessarily had node installed separately. Atom does come bundle with its own version of npm, but not one that you can use. You can get npm by installing node. You can download node from [here](http://nodejs.org/download/)

**Comment by projetmbc** [comment]
In that case, you should add this as a crucial dependency. 

Thanks for your help.

PS: can I ask you a question her about the way your package works ?

**Comment by Galadirith** [comment]
@projetmbc So can I take it that markdown-preview-plus is now working for you?

Yeh of course, what's your question?

**Comment by projetmbc** [comment]
### First debugging with Mac OS 10.8.5 Mountain Lion

npm install fails even with the super user's right. Here are the messages given by npm that does not seem to .

    npm ERR! install Couldn't read dependencies
    npm ERR! Darwin 12.6.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! path /Users/projetmbc/package.json
    npm ERR! code ENOPACKAGEJSON
    npm ERR! errno -2

    npm ERR! package.json ENOENT, open '/Users/projetmbc/package.json'
    npm ERR! package.json This is most likely not a problem with npm itself.
    npm ERR! package.json npm can't find a package.json file in your current directory.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/projetmbc/npm-debug.log

Here is the content of npm-debug.log.

    0 info it worked if it ends with ok
    1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
    2 info using npm@2.5.1
    3 info using node@v0.12.0
    4 verbose config Skipping project config: /Users/projetmbc/.npmrc. (matches userconfig)
    5 error install Couldn't read dependencies
    6 verbose stack Error: ENOENT, open '/Users/projetmbc/package.json'
    6 verbose stack     at Error (native)
    7 verbose cwd /Users/projetmbc
    8 error Darwin 12.6.0
    9 error argv "node" "/usr/local/bin/npm" "install"
    10 error node v0.12.0
    11 error npm  v2.5.1
    12 error path /Users/projetmbc/package.json
    13 error code ENOPACKAGEJSON
    14 error errno -2
    15 error package.json ENOENT, open '/Users/projetmbc/package.json'
    15 error package.json This is most likely not a problem with npm itself.
    15 error package.json npm can't find a package.json file in your current directory.
    16 verbose exit [ -2, true ]


### About your package

I'm working on an homemade ASCII language for science writings that will be analyzed by a Python package. I would like to use atom to produce an HTML preview, with MathJaX, of documents using my ASCII language as you do with Markdown.

**Here is my question.** Will it be hard to hack your package so as to achieve my task ?

**Comment by projetmbc** [comment]
### First debugging with Mac OS 10.10.3 Yosemite

Same problem... :-( Here are the messages.

      > runas@2.0.0 install /Users/projetmbc/.atom/packages/markdown-preview-plus/node_modules/pathwatcher/node_modules/runas
      > node-gyp rebuild

      gyp ERR! configure error 
      gyp ERR! stack Error: Python executable "python" is v3.4.2, which is not supported by gyp.
      gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
      gyp ERR! stack     at failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
      gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
      gyp ERR! stack     at ChildProcess.exithandler (child_process.js:735:7)
      gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
      gyp ERR! stack     at maybeClose (child_process.js:1008:16)
      gyp ERR! stack     at Socket.<anonymous> (child_process.js:1176:11)
      gyp ERR! stack     at Socket.emit (events.js:107:17)
      gyp ERR! stack     at Pipe.close (net.js:476:12)
      gyp ERR! System Darwin 14.1.0
      gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
      gyp ERR! cwd /Users/projetmbc/.atom/packages/markdown-preview-plus/node_modules/pathwatcher/node_modules/runas
      gyp ERR! node -v v0.12.0
      gyp ERR! node-gyp -v v1.0.2
      gyp ERR! not ok 
       
      > oniguruma@4.0.0 install /Users/projetmbc/.atom/packages/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
      > node-gyp rebuild

      gyp ERR! configure error 
      gyp ERR! stack Error: Python executable "python" is v3.4.2, which is not supported by gyp.
      gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
      gyp ERR! stack     at failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
      gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
      gyp ERR! stack     at ChildProcess.exithandler (child_process.js:735:7)
      gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
      gyp ERR! stack     at maybeClose (child_process.js:1008:16)
      gyp ERR! stack     at Socket.<anonymous> (child_process.js:1176:11)
      gyp ERR! stack     at Socket.emit (events.js:107:17)
      gyp ERR! stack     at Pipe.close (net.js:476:12)
      gyp ERR! System Darwin 14.1.0
      gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
      gyp ERR! cwd /Users/projetmbc/.atom/packages/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
      gyp ERR! node -v v0.12.0
      gyp ERR! node-gyp -v v1.0.2
      gyp ERR! not ok 
      npm ERR! Darwin 14.1.0
      npm ERR! argv "node" "/usr/local/bin/npm" "install"
      npm ERR! node v0.12.0
      npm ERR! npm  v2.5.1
      npm ERR! code ELIFECYCLE

      npm ERR! runas@2.0.0 install: `node-gyp rebuild`
      npm ERR! Exit status 1
      npm ERR! 
      npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
      npm ERR! This is most likely a problem with the runas package,
      npm ERR! not with npm itself.
      npm ERR! Tell the author that this fails on your system:
      npm ERR!     node-gyp rebuild
      npm ERR! You can get their info via:
      npm ERR!     npm owner ls runas
      npm ERR! There is likely additional logging output above.

      npm ERR! Please include the following file with any support request:
      npm ERR!     /Users/projetmbc/.atom/packages/markdown-preview-plus/npm-debug.log

I can't put the log because it has at least 15000 lines.

**Comment by Galadirith** [comment]
@projetmbc thanks for the log. So looking at you log from [Mountain Lion](https://github.com/Galadirith/markdown-preview-plus/issues/23#issuecomment-73985269) can I ask if you were running `npm` in the directory `~/.atom/packages/markdown-preview-plus`. The line `npm ERR! path /Users/projetmbc/package.json` suggests to me that you were actually running it from `~/`.

The output from [Yosemite](https://github.com/Galadirith/markdown-preview-plus/issues/23#issuecomment-73988832) is actually mush more promising than it looks. We don't have any permission errors, the problem is the version of Python you have installed. I would guess than you need Python `v3.4.2` for your own work, however you can install a `v2.X.X` version of python along side your current version, and still use your `v3.4.2` version for hacking with, and just use the `v2.X.X` for node. You can grab Python `v2.7.9` [here](https://www.python.org/downloads/release/python-279/).

If your happy to install that older version of Python, you'll then want to add an extra option argument to your `npm` call:

````bash
sudo npm install --python=python2.7
````

This will make sure `npm` uses the correct version of Python. Let me know how that goes :D

> Will it be hard to hack your package so as to achieve my task ?

So if you had a Python package that can take as input text, and can spit out html, then it shouldn't be too hard a hack. markdown-preview-plus uses [roaster](https://github.com/gjtorikian/roaster) in its [rendering script](https://github.com/Galadirith/markdown-preview-plus/blob/master/lib/renderer.coffee) to take markdown formated text to html. While I don't have experience of using Python and Javascript together, it shoudln't be much harder than swaping out roaster for you Python parser. I hope that helps :D

**Comment by projetmbc** [comment]
Let's continue this happy quest ;-)
=========================

# On Yosemite

`sudo npm install --python=python2.7` does the job and prints the following lines.

    > oniguruma@4.0.0 install /Users/projetmbc/.atom/packages/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
    > node-gyp rebuild

    child_process: customFds option is deprecated, use stdio instead.
      CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
      CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
      CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
      CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
    ^[[C  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
      CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
      CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
      CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
      CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
      CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
      CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
      CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
      CC(target) Release/obj.target/oniguruma/deps/onig/st.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
      CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
      LIBTOOL-STATIC Release/oniguruma.a
      CXX(target) Release/obj.target/onig_scanner/src/onig-cache.o
      CXX(target) Release/obj.target/onig_scanner/src/onig-result.o
      CXX(target) Release/obj.target/onig_scanner/src/onig-reg-exp.o
      CXX(target) Release/obj.target/onig_scanner/src/onig-scanner.o
      CXX(target) Release/obj.target/onig_scanner/src/onig-scanner-worker.o
      CXX(target) Release/obj.target/onig_scanner/src/onig-searcher.o
      CXX(target) Release/obj.target/onig_scanner/src/unicode-utils-posix.o
      SOLINK_MODULE(target) Release/onig_scanner.node
      SOLINK_MODULE(target) Release/onig_scanner.node: Finished

    > runas@2.0.0 install /Users/projetmbc/.atom/packages/markdown-preview-plus/node_modules/pathwatcher/node_modules/runas
    > node-gyp rebuild

    child_process: customFds option is deprecated, use stdio instead.
      CXX(target) Release/obj.target/runas/src/main.o
      CXX(target) Release/obj.target/runas/src/runas_darwin.o
      CXX(target) Release/obj.target/runas/src/fork.o
      SOLINK_MODULE(target) Release/runas.node
      SOLINK_MODULE(target) Release/runas.node: Finished

    > pathwatcher@3.1.1 install /Users/projetmbc/.atom/packages/markdown-preview-plus/node_modules/pathwatcher
    > node-gyp rebuild

    child_process: customFds option is deprecated, use stdio instead.
      CXX(target) Release/obj.target/pathwatcher/src/main.o
      CXX(target) Release/obj.target/pathwatcher/src/common.o
      CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
      CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_mac.o
      SOLINK_MODULE(target) Release/pathwatcher.node
      SOLINK_MODULE(target) Release/pathwatcher.node: Finished
    highlights@1.2.0 node_modules/highlights
    ├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
    ├── season@5.1.4 (optimist@0.4.0, cson-parser@1.0.8)
    └── first-mate@3.0.0 (event-kit@1.0.2, emissary@1.3.2, oniguruma@4.0.0)

    pathwatcher@3.1.1 node_modules/pathwatcher
    ├── event-kit@1.0.2
    ├── async@0.2.10
    ├── q@1.1.2
    ├── nan@1.6.1
    ├── iconv-lite@0.4.7
    ├── emissary@1.3.2 (mixto@1.0.0, property-accessors@1.1.2, es6-weak-map@0.1.2)
    └── runas@2.0.0

But then, sorry I feel a little guilty :-), `sudo apm rebuild` doesn't work and prints the following errors. The first lines show another problem with my Python 3 version.

    Rebuilding modules ✗
    gyp ERR! configure error 
    gyp ERR! stack Error: Python executable "python" is v3.4.2, which is not supported by gyp.
    gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
    gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
    gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:735:7)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at maybeClose (child_process.js:1008:16)
    gyp ERR! stack     at Socket.<anonymous> (child_process.js:1176:11)
    gyp ERR! stack     at Socket.emit (events.js:107:17)
    gyp ERR! stack     at Pipe.close (net.js:476:12)
    gyp ERR! System Darwin 14.1.0
    gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/projetmbc/.atom/packages/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
    gyp ERR! node -v v0.12.0
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 

    npm ERR! Darwin 14.1.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.21.0" "--arch=x64"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.3.0
    npm ERR! code ELIFECYCLE
    npm ERR! oniguruma@4.0.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the oniguruma@4.0.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the oniguruma package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls oniguruma
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/projetmbc/.atom/packages/markdown-preview-plus/npm-debug.log

**Comment by projetmbc** [comment]
Now that I know where to look for, indeed I do not know that `node` could use Python, I have fixed the `rebuild` problem. I need to type `sudo PYTHON=python2.7 apm rebuild`. This do the job.

So here is a question. Where is the real problem ? `node` ? `amp` ? Both of them ?

I will try to install the package on Mountain Lion in a few minutes.

**Comment by Galadirith** [comment]
> So the real problem would be to call a Python script from node. Am I right ?

Yeh exactly. A place you might like to start is with [python-shell](https://github.com/extrabacon/python-shell). I don't know how good its performance is and their are probably other options, buts its an option :D 

> So here is a question. Who is guilty ? node ? apm ? Both of them ?

So I think there we're really two problems with the installation:

1. **Permissions to read and write stuff**  
    So there are lots of reasons why node or atom might run into such problems but basically if either of them tries to do something that they don't have the permission its not really their fault. I wouldn't be the best person to ask about such things, but if you want to understand more you could have a look at permission related issues for [atom](https://github.com/atom/atom/issues) or [node](https://github.com/joyent/node/issues) 

2. **Python version**  
    My package uses [node-gyp](https://github.com/TooTallNate/node-gyp) and it does actually say in its [installation instructions](https://github.com/TooTallNate/node-gyp#installation) the version of Python that is needed. So really thats my fault for not including it in the installation instructions for [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus). I'll make sure to add that as a requirement in the next version :D 

> Mountain Lion : the problem is still there… Sorry. ;-)

Ok great, nothing to be sorry about at all, we've made a lot of progress and we're nearing the end :D So it looks like you don't have the right build tools installed (another requirement for  [node-gyp](https://github.com/TooTallNate/node-gyp)! sorry). Here are some steps that should fix that:

1. Run `which make` in a terminal. If you get no output thats good, the problem is that you don't have `make`Now do you have [XCode](https://developer.apple.com/xcode/) installed on your Mountain Lion machine? You'll need to have that installed, and then

**Comment by projetmbc** [comment]
## Here comes the sun…

Everything works now on Mountain Lion too. Thanks for the help and the extra informations.

## Python and node

The link you gave to me seems to be exactly what I'm looking for.

**Comment by Galadirith** [comment]
Thats great @projetmbc, I'm really glad everything is working now. There is definitely nothing to feel ashamed about, I still look at node logs with confusion sometimes and I've been using it for a while :D 

If you have any problems in the future please do let me know, and I'll be looking out for your ASCII language preview program :D

**Comment by projetmbc** [comment]
I keep that in mind. Thanks a lot !

**Comment by myhelloos** [comment]
I'm on ubuntu 14.04 gnome with atom 0.175.0
and followed the steps
```
   1. Download markdown-preview-plus from here and inside that archive file you'll find a folder called markdown-preview-plus-1.2.0. Unpack its contents into ~/.atom/packages/markdown-preview-plus such that you now have folders like:

    ~/.atom/packages/markdown-preview-plus/assets
    ~/.atom/packages/markdown-preview-plus/imgs
    ...

    (alternatively if you are comfortable doing it you could git clone markdown-preview-plus into ~/.atom/packages).
   2. Now open a terminal and move to the directory ~/.atom/packages/markdown-preview-plus
   3. Run npm install
   4. Assuming there are no errors run apm rebuild
    If all went well markdown-preview-plus should now be available in Atom.
```
But, I get failed on step 4; the output says:

```
> oniguruma@4.0.0 install /tmp/apm-install-dir-11527-7167-1aux9j2/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild


> runas@2.0.0 install /tmp/apm-install-dir-11527-7167-1aux9j2/node_modules/markdown-preview-plus/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild


Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11527-7167-1aux9j2/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11527-7167-1aux9j2/node_modules/markdown-preview-plus/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/share/atom/resources/app/apm/.apmrc" "--userconfig" "/home/alfred/.atom/.apmrc" "install" "/tmp/d-11527-7167-3z72jg/package.tgz" "--target=0.20.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@4.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@4.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11527-7167-1aux9j2/npm-debug.log
```
