### ISSUE TITLE
Toggle Preview/LaTeX Rendering does not work when text type is set to "LaTeX"

### ISSUE THREAD

**Issue by j4ckhaal** [Galadirith/markdown-preview-plus#232]
I use the package **language-latex** along with this one to give me LaTeX syntax highlighting. These two packages are the only ones I use.

When I toggle the live preview when the text type is set to "Plain Text," the preview appears fine. However, ironically, when I set the text type to "LaTeX" (courtesy of **language-latex**), ironically the preview doesn't come up when I use the menu or the shortcut to enable it.

I assume that this is a bug. Could it kindly be fixed? It's just a little irritating having to change between these two text types all the time. 

Thank you!

**Comment by kysko** [comment]
In the `language-latex` settings, under each grammar you will see a **Scope**. For example, for the _LaTeX Grammar,_ the Scope is `text.tex.latex`.
Now, in the MPP settings, in the **Grammars** box, add that scope. The Preview should now appear when using the LaTeX text type...

Add the scope of other grammars from language-latex if you need them also.

**Comment by j4ckhaal** [comment]
Wow, thank you _very_ much! This is exactly what I wanted. That was one huge annoyance that's finally gone! I can't believe I didn't look in the settings! (Maybe I missed it all the same). Cheers! :)
