### ISSUE TITLE
Code highlight

### ISSUE THREAD

**Issue by chimit** [Galadirith/markdown-preview-plus#245]
There is no syntax highlighting in code blocks. Any chances to see this feature in future releases?

**Comment by weichiche** [comment]
I've got the hightlighted code in preview, as long as I disable the pandoc parser.

However, if I enable pandoc parser with command-line options `--standalone, --highlight-style=espresso`, the code is all gray. Are the command-line options correct?

**Comment by lierdakil** [comment]
#263 and #264 should hopefully fix that.
Note: `--standalone` Pandoc flag is not supported, and I don't think there's a reasonable way to support it.
