### ISSUE TITLE
OCaml syntax highlighting missing

### ISSUE THREAD

**Issue by xialady** [Galadirith/markdown-preview-plus#250]
Hello, 

I started using Markdown to take school notes, in particular for OCaml courses. But it seems I cannot have the syntax highlighting for the language OCaml? I tried with java, bash and python and works perfectly fine (with the \```[language name] [your code]\``` syntax) and it seems to be supported (see [this](http://tinker.kotaweaver.com/blog/?p=152) and the code below using GitHub's Markdown). How to make it work?

```ocaml
let n = read_int ()

let () =
	let p = ref 0 in
	for k = 1 to n do
		let x = Random.float 1. in
		let y = Random.float 1. in
		if x *. x +. y *. y <= 1. then
			p := !p + 1
	done;
	let pi = 4. *. float !p /. float n in
	Printf.printf "%f\n" pi
```

**Comment by lierdakil** [comment]
MPP uses Atom's syntax highlighting. So you just need to install grammar definitions for ocaml. `language-ocaml` or maybe `language-ocaml-fix` (which is actively maintained unlike the former) package will do that.

**Comment by xialady** [comment]
Thank you for your answer! I already have installed `language-ocaml` and I have syntax highlighting in .ml files but not in the writing part (not the preview) of .md files... I tried installing `language-ocaml-fix` and turning the other off, etc. but nothing happened.

**Comment by lierdakil** [comment]
Works for me:
![image](https://cloud.githubusercontent.com/assets/7275622/22746321/6db67c9a-ee34-11e6-91c3-e7135006f588.png)

Bear in mind, this is with the default Markdown parser. Highlighting code blocks with Pandoc parser is kinda broken at the moment.

**Comment by xialady** [comment]
This is what I meant, the C code is highlighted (same for bash, python and java) but not the OCaml code. At least when I convert it in PDF it is highlighted but it quite agreable to have the colors when taking notes.

![image](https://cloud.githubusercontent.com/assets/15806520/22747242/d6f939e4-ee26-11e6-8e7a-9bbbc08ac409.png)

**Comment by lierdakil** [comment]
Oh, this is unrelated to MPP. Highlighting in editor is handled by Markdown grammar, specifically [language-gfm](https://github.com/atom/language-gfm) by default, or, alternatively, [community language-markdown](https://github.com/burodepeper/language-markdown) if you installed it.

**Comment by lierdakil** [comment]
I've taken a quick look, and neither of those defines a scope for `ocaml`. So feel free to open an issue on either of those.

**Comment by lierdakil** [comment]
Note that `language-markdown` will probably update faster, since it's a community package, and not tied to Atom releases as tightly.

**Comment by xialady** [comment]
Oh sorry for the trouble! I did not see that. Thank you for your help, I will look in `language-markdown`. :bowing_woman:
