### ISSUE TITLE
CDN URL for mathjax

### ISSUE THREAD

**Issue by Shreyas94** [Galadirith/markdown-preview-plus#267]
When saving the preview as an html, the link to mathjax reads `//cdn.mathjax.org/mathjax/latest/MathJax.js`. When the saved html file is opened, none of the math renders, and from the console, it is clear that MathJax.js is not being loaded. Changing the url to "http://cdn.mathjax.org/mathjax/latest/MathJax.js" does the trick. I do this manually every time. It would be great if this could be made a permanent fix.

**Comment by lierdakil** [comment]
Huh. I suppose you're opening html file locally, and I didn't think about that. Okay then, I'll push a hotfix shortly.

**Comment by lierdakil** [comment]
Okay, should be fixed with v2.4.3

**Comment by Shreyas94** [comment]
Yes I was opening it locally and printing as a pdf file from the browser, since there doesn't seem to be a direct way of doing that yet

**Comment by lierdakil** [comment]
Actually, there technically should be a way of doing it directly, via https://github.com/travs/markdown-pdf package. But there's a bug in implementation, which is fixed by https://github.com/travs/markdown-pdf/pull/122. Sadly, that package seems unmaintained. I might try to work around that bug on our end at some point though.

**Comment by Shreyas94** [comment]
Does it render math?

**Comment by lierdakil** [comment]
With MPP, it should. But it doesn't actually work at the moment :disappointed:

**Comment by Shreyas94** [comment]
I think I can find time to write up a pdf saving command. Given my busy schedule, I should be able to come up with something by next sunday

**Comment by lierdakil** [comment]
Well, PRs are *always* welcome.

**Comment by Shreyas94** [comment]
Added a [pull request](https://github.com/Galadirith/markdown-preview-plus/pull/272). Just a minor feature add. Solves the problem
