### ISSUE TITLE
Deprecated call when previewing untitled file with pandoc

### ISSUE THREAD

**Issue by susisu** [Galadirith/markdown-preview-plus#273]
When previewing untitled file with pandoc, it causes deprecated call like below.

As far as I examined, it seems because `TextEditor::getPath()` returns `undefined` for untitled file ([markdown-preview-view.coffee:213](https://github.com/Galadirith/markdown-preview-plus/blob/55af3429043057a7322e882b48f2eba4d467f47f/lib/markdown-preview-view.coffee#L213)) and it is passed to `path.dirname` directly ([pandoc-helper.coffee:48](https://github.com/Galadirith/markdown-preview-plus/blob/55af3429043057a7322e882b48f2eba4d467f47f/lib/pandoc-helper.coffee#L48)).

---

Argument to `path.dirname` must be a string
```
Object.dirname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
setPandocOptions (~/.atom/packages/markdown-preview-plus/lib/pandoc-helper.coffee:73:28)
Object.renderPandoc (~/.atom/packages/markdown-preview-plus/lib/pandoc-helper.coffee:199:5)
render (~/.atom/packages/markdown-preview-plus/lib/renderer.coffee:80:27)
Object.toDOMFragment (~/.atom/packages/markdown-preview-plus/lib/renderer.coffee:34:12)
MarkdownPreviewView.renderMarkdownText (~/.atom/packages/markdown-preview-plus/lib/markdown-preview-view.coffee:323:23)
```

**Comment by lierdakil** [comment]
Thanks for reporting!
