### ISSUE TITLE
install failed on Atom 0.189.0 ,windows 7

### ISSUE THREAD

**Issue by maplewizard** [Galadirith/markdown-preview-plus#31]
Hi, I want to install markdown-preview-plus on Atom 0.189.0 ,windows 7 and get the following error:

```
Installing “markdown-preview-plus@1.3.0” failed.Hide output…

> runas@2.0.0 install C:\Users\maple\AppData\Local\Temp\apm-install-dir-11535-4604-541xia\node_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\maple\AppData\Local\Temp\apm-install-dir-11535-4604-541xia\node_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas>node "C:\Users\maple\AppData\Local\atom\app-0.189.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
�ڴ˽��򷽰���һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\maple\AppData\Local\Temp\apm-install-dir-11535-4604-541xia\node_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas\build\binding.sln]

> oniguruma@4.2.0 install C:\Users\maple\AppData\Local\Temp\apm-install-dir-11535-4604-541xia\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\maple\AppData\Local\Temp\apm-install-dir-11535-4604-541xia\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>node "C:\Users\maple\AppData\Local\atom\app-0.189.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
�ڴ˽��򷽰���һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\maple\AppData\Local\Temp\apm-install-dir-11535-4604-541xia\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\binding.sln]

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\maple\\AppData\\Local\\atom\\app-0.189.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\maple\\AppData\\Local\\atom\\app-0.189.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\maple\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\maple\\.atom\\.apmrc" "install" "C:\\Users\\maple\\AppData\\Local\\Temp\\d-11535-4604-1e16e6k\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

How can I solve this problem?

**Comment by pedritomelenas** [comment]
Same problem with Windows 8 and version 0.190.0
```
Installing “markdown-preview-plus@1.3.0” failed 
```

**Comment by hiro4bbh** [comment]
This can be solved with atom editor in Administrator mode.
However, error on installing oniguruma package happens (Windows 8.1 and version 0.190.0).

**Comment by Galadirith** [comment]
Hey @maplewizard @pedritomelenas @hiro4bbh I'm incredibly sorry that I haven't been able to get back to you all on this issue sooner.

I have just rolled out new version of MPP `v1.4.0`. In particular I have added more detail to the [Installation Instructions](https://github.com/Galadirith/markdown-preview-plus#installation-instructions) in the new version so please check there and it might be that you have a required program missing.

I have actually been having problems with test installations myself and having installed [Microsoft Visual Studio Express 2013 for Windows Desktop](http://go.microsoft.com/?linkid=9816758) seems to have done the trick at fixing it. So if after having checked the installation requirements and MPP still isn't installing for you, you could try installing VSE 2013.

Please let me know how it goes, and if their are still problems please let me know and we can dig a little deeper to find the root of the issue :D

**Comment by bgatessucks** [comment]
I had similar errors when upgrading 1.4.0 in atom 0.190. I installed VSE 2013 and was able to update MPP.

**Comment by Galadirith** [comment]
@maplewizard @pedritomelenas @hiro4bbh I hope that your no longer experiencing the installation issue on your OS's. As its been over a month since the last comment from @bgatessucks confirming that VSE 2013 fixed the issue for similar errors I'm closing the issue. But if you are still experiencing the issue please post back and I would be very happy to look further into it :D

**Comment by pedritomelenas** [comment]
Thank for your message. I tried under windows and got some issues, but 
fortunately I do not have to use that machine frequently; I use Mac  OS and 
linux mint, where it works fine.
I will give another try in windows when I get back to that machine, and 
will let you know.
Thanks

Enviado con Aquamail para Android
http://www.aqua-mail.com


El 9 de julio de 2015 7:33:11 p. m. Edward Fauchon-Jones 
<notifications@github.com> escribio:
