### ISSUE TITLE
Uncaught Error: Module version mismatch. Expected 43, got 41.

### ISSUE THREAD

**Issue by pedritomelenas** [Galadirith/markdown-preview-plus#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package, v1.3.0

### Stack Trace

Uncaught Error: Module version mismatch. Expected 43, got 41.

```
At ATOM_SHELL_ASAR.js:118

Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/pedro/.atom/packages/markdown-preview-plus/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/pedro/.atom/packages/markdown-preview-plus/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:452:26)
```

### Commands

```
     -0:25.5 core:select-right (atom-text-editor.editor.is-focused)
  7x -0:25.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:21.9 editor:newline (atom-text-editor.editor.is-focused)
     -0:20.1 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:19.6 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:19.2 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:18.3 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.4 core:move-left (atom-text-editor.editor.is-focused)
     -0:14.1 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:13.1 core:move-up (atom-text-editor.editor.is-focused)
 10x -0:10.6 core:select-left (atom-text-editor.editor.is-focused)
     -0:07.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.7 core:move-right (atom-text-editor.editor.is-focused)
     -0:06.4 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.5 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-preview-plus": {
    "enableLatexRenderingByDefault": true
  }
}
```

### Installed Packages

```coffee
# User
language-gap, v0.1.0
markdown-preview-plus, v1.3.0
mathjax-wrapper, v0.1.0

# Dev
No dev packages
```

**Comment by nathanielng** [comment]
This error didn't exist when I was using Atom 0.188.0, but I knew someone who had this problem on Atom 0.189.0.  So I did an upgrade (from 0.188.0 to 0.189.0) to check and yes, I now have this error.

**Comment by pedritomelenas** [comment]
Uninstalling/installing the package solved the problem for me

**Comment by nathanielng** [comment]
thanks! I uninstalled the package and reinstalled it. Now Markdown Preview Plus works fine.

**Comment by szhorvat** [comment]
I'm seeing this problem too now, Atom 0.190.

I'll let you know if uninstall/reinstall fixes it.

**Comment by szhorvat** [comment]
Yes, a reinstall fixed it.  I do wonder why this keeps happening to people though.  I didn't do anything special to Atom that could have caused it.  I just kept updating Atom and the already installed packages until one day I got this error when trying to preview a markdown document.

**Comment by Galadirith** [comment]
Hey Everyone :D @pedritomelenas @nathanielng @szhorvat I really apologise for my long absence and not having been able to get back to you soon.

I think those errors all stemmed from MPP falling behind the development of atom. The API's still changing as the devs move towards the 1.0.0 release, and other dependencies have changed.

I've just rolled a long overdue update that should fix these (and I will endeavour not fall that far behind again ;D)

Please let me know if the error are still appearing and we can take it from there :D

**Comment by pedritomelenas** [comment]
Works perfect now. Thanks!

**Comment by Galadirith** [comment]
Thanks for the update @pedritomelenas, I'm really glad everything's working for you now :smile: Please let us know if you have any issues in the future.
