### ISSUE TITLE
Uncaught Error: error

### ISSUE THREAD

**Issue by OMGtechy** [Galadirith/markdown-preview-plus#35]
1. Open markdown file in Atom
2. Press Control + Shift + M

**Atom Version**: 0.194.0
**System**: Microsoft Windows 8.1
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package, v1.3.0

### Stack Trace

Uncaught Error: error: 127C:\Users\techn_000\.atom\packages\markdown-preview-plus\node_modules\pathwatcher\build\Release\pathwatcher.node

```
At ATOM_SHELL_ASAR.js:118

Error: error: 127C:\Users\techn_000\.atom\packages\markdown-preview-plus\node_modules\pathwatcher\build\Release\pathwatcher.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\techn_000\.atom\packages\markdown-preview-plus\node_modules\pathwatcher\lib\main.js:6:13)
    at Object.<anonymous> (C:\Users\techn_000\.atom\packages\markdown-preview-plus\node_modules\pathwatcher\lib\main.js:207:4)
```

### Commands

```
     -2:29.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:22.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:57.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:57.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:20 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -0:15.8.0 core:confirm (atom-text-editor.editor.mini)
     -0:10.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:09.1.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-preview-plus": {}
}
```

### Installed Packages

```coffee
# User
markdown-preview-plus, v1.3.0

# Dev
No dev packages
```

**Comment by Galadirith** [comment]
@OMGtechy Thanks for catching that, and I'm really sorry its taken me 2 weeks to get back to you.

I've just pushed out a new version of MPP `1.4.0` that should fix this issue. Please let me know if the new version resolves this for you :D

**Comment by Galadirith** [comment]
@OMGtechy As its been over a month since my last comment I hope that everything is now working for you so I will close the issue. However if your still experiencing the issue please feel free to post back and I will be happy to take another look :D

**Comment by OMGtechy** [comment]
Sorry for the late reply, I just used the auto bug report feature and forgot about it!
I don't use Atom so often anymore, and no longer have access to the machine that the issue was produced on.

Thank you for (hopefully?) fixing it!

**Comment by GAMELASTER** [comment]
@Galadirith I got this problem on my application but I cant find a solution, please can you say me how to fix it?
