### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by Camypaper** [Galadirith/markdown-preview-plus#40]
I failed the installation of markdown-preview-plus. How should I do?

Output:
> runas@2.0.0 install C:\Users\CAMYPA~1\AppData\Local\Temp\apm-install-dir-11555-6912-15qb1vn\node_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\CAMYPA~1\AppData\Local\Temp\apm-install-dir-11555-6912-15qb1vn\node_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas>node "C:\Users\camypaper\AppData\Local\atom\app-0.206.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

> oniguruma@4.2.2 install C:\Users\CAMYPA~1\AppData\Local\Temp\apm-install-dir-11555-6912-15qb1vn\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild

C:\Users\CAMYPA~1\AppData\Local\Temp\apm-install-dir-11555-6912-15qb1vn\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>node "C:\Users\camypaper\AppData\Local\atom\app-0.206.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\camypaper\\AppData\\Local\\atom\\app-0.206.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\camypaper\\AppData\\Local\\atom\\app-0.206.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\camypaper\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\camypaper\\.atom\\.apmrc" "install" "C:\\Users\\CAMYPA~1\\AppData\\Local\\Temp\\d-11555-6912-eoqh9h\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by innovateworld** [comment]
@Camypaper Do you have python 2.7 installed?  I received the same error while running python 3.4. Under the documentation for node-gyp they specify python 2.7 be used. After doing so I didn't receive anymore error.

**Comment by Camypaper** [comment]
@innovateworld  Thanks! After I installed python 2.x, I succeeded install of this package.

**Comment by Galadirith** [comment]
@Camypaper I'm very sorry that I wasn't able to respond to you sooner to help you install MPP but im very glad you've been able to resolve. Thanks so much @innovateworld for helping out.

Please let me know if you run into any more problems :D
