### ISSUE TITLE
Is there a easy to override font-family using atom custom stylesheet

### ISSUE THREAD

**Issue by zhsj** [Galadirith/markdown-preview-plus#44]
[help wanted]

I'm using MPP to display some texts containing CJK, but however it can't show CJK characters.

So is there any easy way to override the default font-family?

I use this

```
.markdown-preview, {
    font-family: "Noto Sans CJK SC" !important;
}
```

but still some blocks are not shown well, like `h1`, `code`, etc.

**Comment by zhsj** [comment]
I find an ugly way to do,

```
.markdown-preview,
.markdown-preview *
{
    font-family: "Noto Sans CJK SC" !important;
}
```

It just works temporarily. I'm not sure whether it works for all blocks.

**Comment by Galadirith** [comment]
@zhsj Your solution looks like it should work, but if you run into problems then I have a couple of other suggestions, the first of which I use myself to customize my markdown preview styles.

The first is copy the contents of [`markdown-preview.less`](https://github.com/Galadirith/markdown-preview-plus/blob/c3402fd6b476c6dae0502d546c4b1d63e4cc7e8d/styles/markdown-preview.less) into your `styles.less` and then change the [`@font-family`](https://github.com/Galadirith/markdown-preview-plus/blob/c3402fd6b476c6dae0502d546c4b1d63e4cc7e8d/styles/markdown-preview.less#L3) to what you need.

Alternatively you could modify the `.less` file of your installation of MPP directly. To do that go to **File &rsaquo; Settings &rsaquo;Packages** and then clicking on **Settings** for `markdown-preview-plus` and then clicking on **View Code**. This will open up your local installation of MPP. Then open up the file `./styles/markdown-preview.less` and edit the `@font-family` there. The problem with this way is that this will be overwritten every time you install a new version of MPP.

Hopefully that should work for you. Let me know hope everything goes :D

**Comment by zhsj** [comment]
@Galadirith thanks for reply.

Maybe the CJK problem is atom's bug.

in `markdown-preview.less`, the default font is
``` css
@font-family: "Helvetica Neue", Helvetica, sans-serif;
```

So it should use default sans-serif font that cat render CJK characters but it failed.

however I use the below snippet putting in `~/.atom/styles.less` to work around.

```
@cjk-font: "Noto Sans CJK SC";
.markdown-preview
{
    font-family: @cjk-font;
    atom-text-editor {
        font-family: "Source Code Pro", @cjk-font;
    }
    h1, h2, h3, h4, h5, h6 {
        font-family: "Source Code Pro", @cjk-font;
    }
}
```

**Comment by JosuaCarl** [comment]
The "styles" file did not change anything for me. Probably doing it wrong, but if anyone is contempt with a not so clean solution, here is mine: I edited the body section in .atom/markdown-preview-plus/client/template.html like this:
`font-family: "Arial", sans-serif;`

**Comment by lierdakil** [comment]
https://github.com/atom-community/markdown-preview-plus/blob/master/docs/styling-preview.md
