### ISSUE TITLE
Displaying LaTeX Tables in the Preview

### ISSUE THREAD

**Issue by djbucci** [Galadirith/markdown-preview-plus#46]
Does the current version of markdown-preview-plus support rendering LaTeX tables in the preview window using pandoc? For example, if I drop in...

    \begin{table}
    \begin{tabular}{lcr}
    Number1 & Number2 & Number3 \\
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9 \\
    \end{tabular}
    \end{table} 

and set the markdown flavor to markdown+raw_tex, just the above text renders (with the LaTeX commands). If I run pandoc and output to PDF though (for example), the table shows up.

Thanks for the help, and love the package!

**Comment by Galadirith** [comment]
@djbucci Thanks for checking out MPP :D 

Unfortunately MPP doesn't support rendering LaTeX tables. MPP uses MathJax to process the LaTeX blocks in markdown documents. The environments it supports are limited to those that can be used in maths environments in a normal LaTeX document. You can find a list of all the supported environments [here](http://docs.mathjax.org/en/latest/tex.html#environments).

The best solution to get close to a tabular environment is the [array environment](https://github.com/mathjax/mathjax-docs/wiki/LaTeX-Tabular-environment) that is supported.

I'm sorry its likely not the answer you were hoping for, but please do post back if you had any other questions. Thanks @djbucci.

**Comment by djbucci** [comment]
No problem! It would actually be very helpful to have this link on the main page for MPP for added context. 

Thanks again!

**Comment by Galadirith** [comment]
Thanks @djbucci. That is a great suggestion and an oversight on my part, I'll make sure its there in the next release :D

**Comment by leipert** [comment]
Sorry that I am late to the party. @djbucci, actually the pandoc option `+raw_tex` is not supported in HTML output, as you can find find the [pandoc documentation](http://pandoc.org/README.html#raw-tex):

> Inline LaTeX is ignored in output formats other than Markdown, LaTeX, and ConTeXt

You can see this best in this minimal example.
```markdown
### Test raw_tex

The cake was \emph{huge} for a cup cake
```

If you have `+raw_tex` enabled, raw latex will be stripped:

<img width="218" alt="screen shot 2015-07-24 at 06 18 19" src="https://cloud.githubusercontent.com/assets/2906107/8867609/ea016962-31cb-11e5-8f88-acbbd60026cb.png">


If you have `-raw_tex` disabled:

<img width="316" alt="screen shot 2015-07-24 at 06 18 36" src="https://cloud.githubusercontent.com/assets/2906107/8867610/eb2789a2-31cb-11e5-818e-78c240ada581.png">


@Galadirith, maybe we also should add this to the pandoc part of the documentation.

**Comment by Galadirith** [comment]
@leipert thanks so much for the input. I definitely think adding that to the documentation would be beneficial. Perhaps just adding a couple of subsections to the top of [**Usage**](https://github.com/Galadirith/markdown-preview-plus/blob/dfbd2055d67ab39a556e1a5093a2716604369841/README.md#usage) would be appropriate; **Supported Pandoc features** and **Supported LaTeX commands**.
