### ISSUE TITLE
pandoc --filter option not recognized

### ISSUE THREAD

**Issue by oli-obk** [Galadirith/markdown-preview-plus#48]
I added "--filter path/to/executable" to the pandoc options, but markdown-preview-plus must pass it weirdly to pandoc, since it gives the error

```
pandoc exited with code 2: pandoc: unrecognized option `--filter path/to_executable'
Try pandoc --help for more information.
```

while adding the argument to pandoc in the terminal works fine.

what I need this for is converting code sections with the `graphviz` tag to `png` images and replacing the code sections with the image.

**Comment by leipert** [comment]
will have a look this evening :)

**Comment by oli-obk** [comment]
amusingly it works if I add a comma between `--filter` and `path/to/exe`... (as suggested for multiple options) Not sure what the good way forward would be here...

**Comment by leipert** [comment]
Is it possible, that `--filter=path/to/exe` works?

**Comment by oli-obk** [comment]
indeed it does.

**Comment by oli-obk** [comment]
now I just need to figure out why my images are cached ;) as long as the name doesn't change, the previewed image stays the same, even if I delete the actual image.

**Comment by leipert** [comment]
Okay. Then it has probably something to do with how atom parses the [settings field](https://github.com/Galadirith/markdown-preview-plus/blob/master/lib/main.coffee#L64-L70).

I think I will just add it to the documentation that you need to write it with an `=`.

Could you add a separate issue for the caching (I already got that as well)
