### ISSUE TITLE
The module won't render latex document

### ISSUE THREAD

**Issue by webanck** [Galadirith/markdown-preview-plus#5]
Hi, I tried this atom package - good idea btw - but when I toggle Latex Rendering (ctrl-shift-m), nothing happens.
I disabled the built-in Markdown Preview and checked the package works with a plain text file but not with Latex files.
Any idea?

I have a tex-live installation of Latex and use the atom (0.154.0) package for ubuntu trusty version.
The Markdown Preview Plus version is 0.3.0.

**Comment by OMGtechy** [comment]
I came here thinking the same thing; perhaps it could be made clearer somehow that this is __not__ a LaTex previewer, but simply a Markdown previewer with extra sugar on top?

**Comment by Galadirith** [comment]
@OMGtechy really sorry about, that was definitely not my intention. What would be really useful is if you could tell me what originally made you think it could render a pure LaTeX document. Hopefully that will make sure no one gets confused in the future :D

**Comment by webanck** [comment]
@Galadirith Well, I found your package in the package manager of Atom and it's description made me think it was adding some latex preview to the markdown preview package. That's it for me.

**Comment by Galadirith** [comment]
Thanks @webanck, I really appreciate the comments. Perhaps then simply:

````
Markdown + Mathematics preview in Atom
````

**Comment by OMGtechy** [comment]
When I read it, my mind saw "markdown AND latex previewer". The markdown
and mathematics suggestion is a good one!

**Comment by Galadirith** [comment]
Thanks for the input @OMGtechy :D
