### ISSUE TITLE
Support determinate citation file choosing

### ISSUE THREAD

**Issue by gitkrax** [Galadirith/markdown-preview-plus#50]
Currently, citation files are searched recursively from a path with the assumption that they will be in the same path as the markdown file.

I have one large citation file that I use for all my papers -- it is updated by Mendeley, so I never touch it manually. Choosing the location where that file is causes Atom to crash, either because it is too big or because the path is outside the folder where the markdown file is. I tested it out by symlinking it to the folder where the markdown file is. While it absolutely kills the processor, it doesn't crash and the preview is parsed correctly. Therefore, it seems that the problem is with the path being outside the working directory.

I tried the same thing with a csl-file and it also seems to behave similarly: a path outside the working folder is not recognized, symlinking works.

It would be great if you could determine a folder where the needed files are and not rely on a recursive search that assumes they are within the same path.

**Comment by leipert** [comment]
I will have a look. Are you on Windows or Mac? 

The recursive works it's way up the directory. Where are you `*.bib` and `*.csl` located relative to your home directory and where is the paper working directory relative to your home directory?

If I understand you correctly, you want to specify the directory absolutely. What do you think of the following workflow:

1. Specify an option "citation fallback" in settings.
2. Only look for `*.bib` and `*.csl` recursively from the file up to the dir where atom is in.
3. If it is not found, use `*.bib` and `*.csl` in the fallback dir.

I understand that it makes your cpu sweat, because every change in the markdown file triggers a complete render by pandoc, if the preview is open.

**Comment by leipert** [comment]
Regarding the last point, maybe we should add a debounce that you can change, so that the markdown just gets rendered every x milliseconds.

**Comment by gitkrax** [comment]
I'm on Linux and Windows. I haven't yet tested this package on Windows, because I can't get it to install.

The paper is in

`/home/username/Dropbox/publications/paperfolder/papername.md` (or equivalent)

The bib-file is

`/home/username/Dropbox/Bibtex/library.bib` (note that it is not `bibliography.bib` as assumed now -- the name is autogenerated and I can't change it)

and csl is

`/home/username/.pandoc/csl/apa.csl`

I think the suggested solution is perfect. That would account for the use-case that is presumed now, but support having the data elsewhere (I store my csl-files in the pandoc data folder). I think it should support different locations for both, because that is how I currently work.

I don't think stressing the cpu is a problem -- I just disable live preview and check the result whenever I need to. Every added letter doesn't need to be updated in real-time. An option to disable the fuzzy search might save a few cycles.

**Comment by leipert** [comment]
Will fix it until sunday.

**Comment by gitkrax** [comment]
Excellent work! Tested it out and it works.

Pandoc-citeproc doesn't seem to respect the locale setting in the file YAML-section, so the citations are not localized, but that seems like a minor issue.

**Comment by jaspervanm** [comment]
I still have some problems with using the correct bibliography and/or CSL file: it always refers to the fallback option, regardless of what I put into the settings (bibliography.bib, which lives one folder above the markdown file; or reference-style.csl which lives in the same directory) or what's in the YAML-section.

What can I do to provide an example?
I'm on OSX.
