### ISSUE TITLE
Make sure our macro extension works with pandoc

### ISSUE THREAD

**Issue by leipert** [Galadirith/markdown-preview-plus#54]
PR #14 should also work with pandoc

**Comment by Galadirith** [comment]
> We just have to have a look for 2.0.0, how we handle #14 in pandoc. We have to add it to each document. 
> *- #52* 

Why does pandoc need to know about the macro's?

**Comment by leipert** [comment]
That's actually a good question :dancer: 

If we want to tackle a pandoc pdf export, it needs to know it though :) But it brings me to the question how pandoc hands macros to mathjax if you define them with `\newcommand` in the markdown.

All I am saying with this issue, we have to have a look if #14 works good with pandoc.

**Comment by Galadirith** [comment]
Ah ok I see :D That was my fault for trivialising a multi faceted issue.

On the question of `\newcommand` as a quick test I ran this file `math.md`:
```markdown
\newcommand{\testing}[1]{This is a #1}
$a^2 + b^2 = c^2 \testing{test}$
```
against
```bash
$ pandoc math.md --mathjax
```
and got 
```html
<p><span class="math">\(a^2 + b^2 = c^2 {This is a test}\)</span></p>
```
So Pandoc is already expanding any macros in equation blocks for us. Does MathJax need to know the macro definitions? If you wanted them to be available globally then yes, but actually I think this behaviour is exactly as I would want it. It means we have a natural way to localize macro's to individual files, and we don't have to get our hands messy with MathJax at all :D 

I didn't know pandoc could do that, so I think that's pretty kl, but please let know your thoughts :D

**Comment by leipert** [comment]
@Galadirith Tested #14 with pandoc - works like a charm
