### ISSUE TITLE
Regression on image caching

### ISSUE THREAD

**Issue by Galadirith** [Galadirith/markdown-preview-plus#60]
@leipert I like your changes moving as much logic as possible to the pathwatcher listener in 7c0949f but there is a regression on deleted images (which I should have added a spec for, my fault). Steps to reproduce:

1. Preview an image
2. Modify the image bumping query to `?v=2`
3. Delete the image setting query to `?v=deleted`
4. Restore image however it sets the query to `?v=1`

Part of the problem is that [`iv > 0`](https://github.com/Galadirith/markdown-preview-plus/commit/7c0949f8f8c421cbe8df8e895673c476e424e8c8#diff-3672d5a10a4a059ffc23c46b46cacd2cR99) evaluates as false if `iv` is `deleted` or `renamed`. But simply conditioning on that is likely to cause similar regressions after further delete restore cycles.

A possible design to fix would be to push the version to `imgVersion[src][1]` if the event is not `change` and restore that version when the image is restored, although I don't know which of the three events is triggered when an image is restored, I would guess `change` by the steps experienced above.

Thanks @leipert :D

**Comment by leipert** [comment]
Actually that is really what I wanted :dancer:
What about using unix timestamp instead of an integer

**Comment by Galadirith** [comment]
Oh ha of course, there is nothing else that condition could be checking for, ok :D. 

So the only problem then is that resetting the query to `?v=1` is that then uses the `?v=1` cache from before the image was deleted.

I like the unix timestamp idea a lot, solves the problem without adding any extra logic to `resolveImagePaths()`, great :D

**Comment by Galadirith** [comment]
Surprisingly the specs didn't pass for me @ 7c0949f. The issue seemed to be that on Windows when [`fs.renameSync()`](https://github.com/Galadirith/markdown-preview-plus/commit/7c0949f8f8c421cbe8df8e895673c476e424e8c8#diff-6175cf4a3defa748e7cd74bcc1d6a12aR291) is invoked a `rename` event is fired followed immediately by a `change` event; I don't know weather its a different order on OSX or simply that only `rename` fires. Again my fault for not having a spec to test renaming in the first place.

I think this can be fixed easily enough by decoupling the debounce from the listener and applying just to triggering a rerender.

**Comment by Galadirith** [comment]
@leipert let me know if you wanted me to handle these changes and if you wanted me to integrate the minor changes sitting on a486279 :D

**Comment by leipert** [comment]
#59 is merged, just needs #60 to be working really great.

If you want, do those changes!

**Comment by Galadirith** [comment]
Great, will handle them shortly :D
