### ISSUE TITLE
Create continuous integration accounts. 

### ISSUE THREAD

**Issue by leipert** [Galadirith/markdown-preview-plus#61]
@Galadirith With the merge of #59 we added support for continuous integration (CI). That means automatic testing for OSX, Windows and Linux on every push/pull request. Unfortunately we need three providers for that, fortunately they are all free for OpenSource Projects.

As I am not the admin for this package, either move the mpp development to a Github organization or you (@Galadirith) need to setup the CI accounts:

* [travis ci](https://travis-ci.org/) for OSX testing
* [appvejor](http://www.appveyor.com/) for Windows testing
* [wercker](https://app.wercker.com) for Linux (Ubuntu) testing

Every CI provider above should work out of the box with MPP.
If you want I can assist you with setup of the accounts/repo through a Skype session.

**Comment by Galadirith** [comment]
That fantastic :D All accounts created and webhooks fixed for wercker. 

travis has rebuilt for current travis CI enabled PR's (which is only #62). As both wercker and appvejor use webhooks not services I can't see a way to manually trigger a rebuild, maybe its not possible? But I suppose thats really only an issue for the 2 currently active PR's until they have further commits pushed.

Thank so much for adding all this CI support @leipert

**Comment by Galadirith** [comment]
@leipert Is it an issue that wercker is failing? I can't figure out from the log's alone why its failing.

**Comment by leipert** [comment]
@Galadirith Just ignore wercker for the time being, I will have a look once 1.7.0 is pushed to the users.
