### ISSUE TITLE
create pathwatcher version without runas

### ISSUE THREAD

**Issue by leipert** [Galadirith/markdown-preview-plus#67]
As [pathwatcher](https://www.npmjs.com/package/pathwatcher) causes a lot of trouble (namely #43, #45, #46). Maybe we could migrate away from it?
Alternatives would be:

* https://www.npmjs.com/package/chokidar
* https://www.npmjs.com/package/watchr
* https://www.npmjs.com/package/watch

**Comment by leipert** [comment]
I did some extensive research. We do not want to move away from pathwatcher.

I will give a quick overview over file watching in node.

First we have fs.watch / fs.watchFile from node. These are unreliable and ugly. Therefore alternatives like [chokidar](https://www.npmjs.com/package/chokidar), [watchr](https://www.npmjs.com/package/watchr) and [watch](https://www.npmjs.com/package/watch) do build a wrapper around it, which makes things nicer.

[pathwatcher](https://www.npmjs.com/package/pathwatcher) compiles a tiny c program depending on which platform you are and works fine on all mac, win and linux, why it doesn't work on wercker is explained #68. It's a bug on wercker and from pathwatcher.

pathwatcher however has a dependency to runas, which leads to the failing in #43, #45 and #46. As runas is just used in one tiny `writeFile` [edge case](https://github.com/atom/node-pathwatcher/blob/849e893fbe3a1f7d21b9c06318c1aa94330526a4/src/file.coffee#L317-L328) on mac osx only. I am preparing a fork of pathwatcher without the runas dependency, which will cause no install troubles anymore.

**Comment by Galadirith** [comment]
Thats amazing work @leipert thanks so much for the detailed information, and I would imagine that [`pathwatcher-without-runas`](https://github.com/leipert/node-pathwatcher-without-runas) is going to have a great impact well beyond MPP :D

**Comment by leipert** [comment]
Well, we will have to see whether this has an impact or not.

pathwatcher also needs node-gyp to compile stuff,
so maybe without runas of breaking at runas,
it will now break at pathwatcher instead. :+1:

We will see.
