### ISSUE TITLE
Lists don't render when Pandoc Parser is enabled

### ISSUE THREAD

**Issue by JonnyCBB** [Galadirith/markdown-preview-plus#71]
Hi,

When I enable the Pandoc parser from the Settings view, I find that lists (unordered or ordered) do not render properly in the preview window but everything else seems to render fine.
It's not a huge problem for me because when I disable the Pandoc parser, everything else works fine.

I'm not sure if this issue is best placed here though but I wasn't sure where else to put it.

Just so you are aware I am running 64 bit, Windows 10 OS if that helps anything

**Comment by Galadirith** [comment]
Thanks @JonnyCBB and sorry lists are behaving oddly for you. It might end up not being an MPP issue but there's absolutely no problem posting here :D we'll see what we can do.

@leipert may well be best place to help you, but I can't seem to reproduce any problem with lists. Here's what I get on Windows 7 64 bit with pandoc enabled ([gist](https://gist.github.com/Galadirith/4209a7a757fa00526fac) for source):
![71](https://cloud.githubusercontent.com/assets/1201875/9272627/630a0452-427c-11e5-8e40-b30eea8bc0d3.png)

If you could try previewing that document and send back a screen shot, or even better the html of the preview as a gist so we can get a clearer picture of the problem we'll have a look :D

As an unrelated comment I noticed your studying at Oxford, I just finished my MMath there, what are you studying?

**Comment by leipert** [comment]
@JonnyCBB, could you provide a minimal document which shows the errors?

**Comment by JonnyCBB** [comment]
Really weird. I started writing some code to send and the list still weren't rendering. I decided to then copy paste the text from @Galadirith's gist and it rendered perfectly. Now it all seems to work even when I make my own lists. 
Sorry to bother you both. If it happens again, I'll let you know but it all seems to be working fine now.

@Galadirith I studied for an MMath too, but I did mine in Southampton University. I'm now doing a DPhil in X-ray Crystallography so I'm in the Biochemistry department here (still working on maths stuff though). Where are you now?

**Comment by Galadirith** [comment]
@JonnyCBB No problem, if it happens again as @leipert said send us a minimal document that causes the problem.

Thats really great, are you part of the DTC? I'm start my PhD at Cardiff in October and joining their Gravitational Waves group.

**Comment by JonnyCBB** [comment]
No problem, I will do.

Yes, I joined the System Biology DTC in 2012. Absolutely loving it. Gravitational Waves!!! That's some hardcore stuff. I did a module in it in Southampton with Nils Andersson. You're a braver man than me to take that up ;)
