### ISSUE TITLE
Shortcut to activate the preview of currently focused editor

### ISSUE THREAD

**Issue by Galadirith** [Galadirith/markdown-preview-plus#74]
Feature request to add a shortcut to activate the preview of the currently focused editor associated with the preview.

**Comment by Galadirith** [comment]
@leipert I actually think the best way to handle this would be simply not to add any new keymaps, but to have `ctrl-shift-M` make the preview active if it is not, otherwise it will simply toggle the preview, let me know your thoughts :D

**Comment by leipert** [comment]
That sounds like a good solution :+1:
Should be a small change as well.
Do you want to take care of it?

**Comment by Galadirith** [comment]
Yep no problem :D
