### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by leipert** [Galadirith/markdown-preview-plus#79]
Prior to releasing 2.0.0, we should add a changelog for easy overview of changes for existing users

**Comment by Galadirith** [comment]
You read my mind on this one :D

**Comment by leipert** [comment]
@Galadirith I will add the Changelog once the 2.0.0 release is made. I found a nice tool for that which I would like to try.

**Comment by Galadirith** [comment]
@leipert Great :D Thanks so much for handling this one and it will be really interesting to see how the tool performs.

**Comment by Galadirith** [comment]
@leipert Everything is ready to go, sorry that its taken me till the early hours of the morning to finish everything. I think I've dealt with everything but please ping me if I've overlooked something/made an error.

If you'd like to add the changelog whenever is convenient and then i'll publish `2.0.0` when I wake up :D
