### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by aclarembeau** [Galadirith/markdown-preview-plus#93]
So, because the screenshot is worth a thousand words (not really sure it's a good ideomatic expression but for me it sound good)
![image](https://cloud.githubusercontent.com/assets/10834626/9652975/8dd024b0-5220-11e5-8733-f05bfc520072.png)
I don't know why it does that on my Linux Mint 17.2 Raphaella but I'd be very happy to help you to discover the origin of the problem :) (it does that to all my files)
PS2: My computer language is French; maybe it's the origin of the problem?

**Comment by Galadirith** [comment]
@aclarembeau Thanks for splitting off a new this issue for this problem :D I'm not able to investigate this at the moment but will update you when I am able to :D

**Comment by leipert** [comment]
@aclarembeau Could you upload the file somewhere, for example in a [gist](gist.github.com) and additionally send me the file to git@leipert.io

**Comment by aclarembeau** [comment]
I'll join the file to this email ( it's just a simple md file with "ééé dd"
as content).
For me, it seems to be a problem with file encoding HTML metadata and atom
HTML reader.
I'll explain why.
The file is encoded as UTF-8 (filei command shows that).
When I run "pandoc file.md" it returns "<p>ééé dd</p>"
But, when I run it as a standalone HTML webpage, "pandoc -s file.md" it
returns
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "
http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
</head>
<body>
<p>ééé dd</p>
</body>
</html>
"
It runs fine on my web browser. I could reasonably think that the pandoc
extension generates the same HTML code.
So, the only option is that the Atom web browser doesn't handle correctly
utf-8 encoding I've no idea why.

Hope it'll help you :)


2015-09-03 17:36 GMT+02:00 Lukas Eipert <notifications@github.com>:

**Comment by leipert** [comment]
@aclarembeau 
I really tried to reproduce your error on OSX, I had no issues. I will try it on LM on a Virtual Machine.

Also the file wasn't attached to your email (seems like gh doesn't support)
Could you please send the file to git@leipert.io?

**Comment by aclarembeau** [comment]
A million apologies, your program works well, I wrote an issue to the wrong
package (markdown package names are so close).. please close this issue.
Sorry for the time wasted :s

2015-09-04 14:15 GMT+02:00 Lukas Eipert <notifications@github.com>:

**Comment by leipert** [comment]
@aclarembeau No problem. Which markdown package are you using and why, if I may ask?

**Comment by aclarembeau** [comment]
https://atom.io/packages/pandoc
Because of full support of pandoc image and latex equations (surrounded by
$ instead of mathjax syntax that I don't like). My use of markdown is to
write university courses so I often need complex structures such as
equations and I must be able to write them fast (it's why I must keep LaTeX
that I already know). So, personnaly, I need a full pandoc support .

Hope it'll help you :)

2015-09-04 20:23 GMT+02:00 Lukas Eipert <notifications@github.com>:

**Comment by aclarembeau** [comment]
Just to finish: if you add:
- table of contents
- different stylesheets (css files)
- latex equations surrounded by $$
- image support (i think already present)
I should switch directly :)

2015-09-04 20:30 GMT+02:00 Alexis Clarembeau <alexisclarembeau@gmail.com>:

**Comment by leipert** [comment]
@aclarembeau 
latex equations surrounded by $$ and image support are there. See the image:

![screen shot 2015-09-05 at 16 08 33](https://cloud.githubusercontent.com/assets/2906107/9699577/6bfef52c-53e8-11e5-8bd5-466d2181016e.png)

Table of contents seems to work, but a little bit hacky if you set
`Pandoc Options: Commandline Arguments` to:
`--smart, --table-of-contents, --standalone`
Opened issue #102 for that. You can see the result in the image as well.

Different stylesheets is a must as well, we will handle that one in the future.

Thanks for the feedback.

Document from the image:

```markdown
# header

## Test 2

$$
E=mc^2
$$
asd
```

**Comment by aclarembeau** [comment]
Nice, I'll try a bit more your package.
If a can suggest some things:
- I didn't see the latex support because I used HTML rendering. Maybe, you
can unify LaTeX and HTML equation notation by using pandoc HTML latex
equation support (via a js script I don't remember the name)
- I also like pandoc "image with caption" system "![caption](image.png)"
doesn't render a good figure environment with caption with your latex system
- Also, I cannot get easily PDF or HTML with your package; maybe you could
add this option (It should be easily implementable)
    EDIT: I finally saw HTML export option; it should be for me also in the
package menu; contextual menu isn't for me a good choice

Anyway, your support is very good and reactive. You do a great job. Keep on
and this package will be nearly perfect ;)
