### ISSUE TITLE
Diff algorithm is not working for changing OL start

### ISSUE THREAD

**Issue by leipert** [Galadirith/markdown-preview-plus#98]
If i change the start of a ordered list, the view is not updated:

![](http://g.recordit.co/DP2kxc5Bz0.gif)

`<ol start="4">...</ol>` should change to `<ol start="1">...</ol>`

**Comment by leipert** [comment]
@Galadirith Maybe 2.0.2 if you want ;)

**Comment by Galadirith** [comment]
@leipert Thanks for spotting this one. If I can cheekily slip this into `2.0.2` I will, however with [list items](http://spec.commonmark.org/0.22/#list-items) being [container blocks](http://spec.commonmark.org/0.22/#container-blocks) I suspect it will take work that will probably still hold it as a `2.1.0` target.
