### ISSUE TITLE
Initialize markdownIt during image rendering for pandoc users

### ISSUE THREAD

**Issue by leipert** [Galadirith/markdown-preview-plus#99]
Spun of from #97.

If a user uses pandoc and has a file with images [renderer.coffee#L114](https://github.com/Galadirith/markdown-preview-plus/blob/9e6048acca568e1c4d1d7c7218fd9fc6f3a076a8/lib/renderer.coffee#L114) will fail.

**Comment by leipert** [comment]
Not unrelated: Got #99 issues, but a well defined markdown ain't one.

/cc @djbucci

**Comment by Galadirith** [comment]
> Got #99 issues, but a well defined markdown ain't one.

:laughing:
